---
title: ""
documentclass: article

output:
  pdf_document:
    latex_engine: xelatex
    number_sections: true
    includes:
      in_header: header.tex
---

```{r, include=FALSE}
options(knitr.duplicate.label = "allow")
library(httr)
library(readxl)
library(dplyr)
url <- "https://kf.kobotoolbox.org/api/v2/assets/aycXgGj28xx2kp266wNKY9/export-settings/esiBoLNm45SQnB55UZCAmNq/data.xlsx"
tf <- tempfile(fileext = ".xlsx")

my_token <- "5d24ece551cba75bfe9278bff0b4d482bc266b75"

GET(url, 
    write_disk(tf, overwrite = TRUE), 
    add_headers(Authorization = paste("Token", my_token)))


df <- read_excel(tf)




# دالة تحويل الارقام الانكليزية الى العربية
ad <- function(x){
  chartr("0123456789", "٠١٢٣٤٥٦٧٨٩", as.character(x))
}

ay <- "2026/2027"
by <- "2027/2026"


cat(
  paste0("\\fancyfoot[R]{\\large\\bfseries الإحصاء السنوي للعام الدراسي ", ad(by), "}"),
  file = "footer.tex"
)


```
```{=latex}
\tableofcontents
\newpage
\section{رياض الاطفال}
\subsection{التعليم الحكومي}
```
```{r, include=FALSE}
df <- df %>% filter(q18 == 1 & q4 == 1)
```


```{r, child='file//riad-alaitfal//table1.Rmd'}
```
```{r, child='file//riad-alaitfal//table2.Rmd'}
```
```{r, child='file//riad-alaitfal//table3.Rmd'}
```
```{r, child='file//riad-alaitfal//table4.Rmd'}
```
```{r, child='file//riad-alaitfal//table5.Rmd'}
```
```{r, child='file//riad-alaitfal//table6.Rmd'}
```
```{r, child='file//riad-alaitfal//table7.Rmd'}
```
```{r, child='file//riad-alaitfal//table8.Rmd'}
```
```{r, child='file//riad-alaitfal//table9.Rmd'}
```
```{=latex}

\newpage
\subsection{التعليم الاهلي}
\setcounter{table}{0}
```
```{r, include=FALSE}
df <- df %>% filter(q18 == 2 & q4 == 1)
```
```{r, child='file//riad-alaitfal//table1.Rmd'}
```
```{r, child='file//riad-alaitfal//table2.Rmd'}
```
```{r, child='file//riad-alaitfal//table3.Rmd'}
```
```{r, child='file//riad-alaitfal//table4.Rmd'}
```
```{r, child='file//riad-alaitfal//table5.Rmd'}
```
```{r, child='file//riad-alaitfal//table6.Rmd'}
```
```{r, child='file//riad-alaitfal//table7.Rmd'}
```
```{r, child='file//riad-alaitfal//table8.Rmd'}
```
```{r, child='file//riad-alaitfal//table9.Rmd'}
```
