```{r table_v2_5, include=FALSE}

c11 <- nrow(df[which(df$q6 == "1" &df$q20 == "1"),])
c12 <- nrow(df[which(df$q6 == "2" &df$q20 == "1"),])
c13 <- c11 + c12

c21 <- nrow(df[which(df$q6 == "1" &df$q20 == "2"),])
c22 <- nrow(df[which(df$q6 == "2" &df$q20 == "2"),])
c23 <- c21 + c22

c31 <- nrow(df[which(df$q6 == "1" &df$q20 == "3"),])
c32 <- nrow(df[which(df$q6 == "2" &df$q20 == "3"),])
c33 <- c31 + c32 

c41 <- c11 + c21 + c31
c42 <- c12 + c22 + c32
c43 <- c41 + c42 

c51 <- sum(df$table25a_32[df$q6 == "1"], na.rm = TRUE)
c52 <- sum(df$table25a_32[df$q6 == "2"], na.rm = TRUE)
c53 <- c51 + c52

c61 <- sum(df$table25a_33[df$q6 == "1"], na.rm = TRUE)
c62 <- sum(df$table25a_33[df$q6 == "2"], na.rm = TRUE)
c63 <- c61 + c62

c71 <- c51 + c61
c72 <- c52 + c62
c73 <- c71 + c72



```

\begin{table}[H]
\centering
\caption{عدد الشعب للعام الدراسي 2026/2025 حسب الصف والجنس (الصباحي والمسائي)}
\begin{tabular}{@{}|c|cccc|@{}}
\toprule
\multirow{3}{*}{الصف} & \multicolumn{4}{c|}{عدد الشعب حسب الصف والجنس}                                                                                                                   \\ \cmidrule(l){2-5} 
                      & \multicolumn{1}{c|}{\multirow{2}{*}{بنون}} & \multicolumn{1}{c|}{\multirow{2}{*}{بنات}} & \multicolumn{1}{c|}{\multirow{2}{*}{مختلط}} & \multirow{2}{*}{المجموع} \\
                      & \multicolumn{1}{c|}{}                      & \multicolumn{1}{c|}{}                      & \multicolumn{1}{c|}{}                       &                          \\ \midrule
الاول   المتوسط       & \multicolumn{1}{c|}{565}                   & \multicolumn{1}{c|}{533}                   & \multicolumn{1}{c|}{8}                      & 1106                     \\ \midrule
الثاني   المتوسط      & \multicolumn{1}{c|}{498}                   & \multicolumn{1}{c|}{527}                   & \multicolumn{1}{c|}{9}                      & 1034                     \\ \midrule
الثالث   المتوسط      & \multicolumn{1}{c|}{479}                   & \multicolumn{1}{c|}{502}                   & \multicolumn{1}{c|}{8}                      & 989                      \\ \midrule
الرابع   العلمي       & \multicolumn{1}{c|}{311}                   & \multicolumn{1}{c|}{396}                   & \multicolumn{1}{c|}{7}                      & 714                      \\ \midrule
الرابع   الادبي       & \multicolumn{1}{c|}{37}                    & \multicolumn{1}{c|}{33}                    & \multicolumn{1}{c|}{3}                      & 73                       \\ \midrule
الرابع   الفنون       & \multicolumn{1}{c|}{0}                     & \multicolumn{1}{c|}{0}                     & \multicolumn{1}{c|}{0}                      & 0                        \\ \midrule
الخامس   العلمي       & \multicolumn{1}{c|}{237}                   & \multicolumn{1}{c|}{324}                   & \multicolumn{1}{c|}{8}                      & 569                      \\ \midrule
الخامس   الفنون       & \multicolumn{1}{c|}{0}                     & \multicolumn{1}{c|}{0}                     & \multicolumn{1}{c|}{0}                      & 0                        \\ \midrule
الخامس   الادبي       & \multicolumn{1}{c|}{23}                    & \multicolumn{1}{c|}{24}                    & \multicolumn{1}{c|}{2}                      & 49                       \\ \midrule
السادس   العلمي       & \multicolumn{1}{c|}{210}                   & \multicolumn{1}{c|}{218}                   & \multicolumn{1}{c|}{4}                      & 432                      \\ \midrule
السادس   الفنون       & \multicolumn{1}{c|}{0}                     & \multicolumn{1}{c|}{0}                     & \multicolumn{1}{c|}{0}                      & 0                        \\ \midrule
السادس   الادبي       & \multicolumn{1}{c|}{26}                    & \multicolumn{1}{c|}{24}                    & \multicolumn{1}{c|}{2}                      & 52                       \\ \midrule
المجموع               & \multicolumn{1}{c|}{2386}                  & \multicolumn{1}{c|}{2581}                  & \multicolumn{1}{c|}{51}                     & 5018                     \\ \bottomrule
\end{tabular}%
\end{table}