```{r table_v2_2, include=FALSE}

c11 <- nrow(df[which(df$q6 == "1" &df$q20 == "1"),])
c12 <- nrow(df[which(df$q6 == "2" &df$q20 == "1"),])
c13 <- c11 + c12

c21 <- nrow(df[which(df$q6 == "1" &df$q20 == "2"),])
c22 <- nrow(df[which(df$q6 == "2" &df$q20 == "2"),])
c23 <- c21 + c22

c31 <- nrow(df[which(df$q6 == "1" &df$q20 == "3"),])
c32 <- nrow(df[which(df$q6 == "2" &df$q20 == "3"),])
c33 <- c31 + c32 

c41 <- c11 + c21 + c31
c42 <- c12 + c22 + c32
c43 <- c41 + c42 

c51 <- sum(df$table25a_32[df$q6 == "1"], na.rm = TRUE)
c52 <- sum(df$table25a_32[df$q6 == "2"], na.rm = TRUE)
c53 <- c51 + c52

c61 <- sum(df$table25a_33[df$q6 == "1"], na.rm = TRUE)
c62 <- sum(df$table25a_33[df$q6 == "2"], na.rm = TRUE)
c63 <- c61 + c62

c71 <- c51 + c61
c72 <- c52 + c62
c73 <- c71 + c72



```

\begin{table}[H]
\centering
\caption{عدد المدارس والطلبة المقبولين الجدد والموجودين وعدد اعضاء الهيئة التدريسية}
\resizebox{\textwidth}{!}{%
\begin{tabular}{@{}|c|cccc|cccccccccccc|ccc|ccc|@{}}
\toprule
\multirow{4}{*}{الموقع البيئي} & \multicolumn{4}{c|}{\multirow{3}{*}{عدد   المدارس}}                                          & \multicolumn{12}{c|}{عدد الطلبة المقبولين الجدد}                                                                                                                                                                                                                                                                                     & \multicolumn{3}{c|}{\multirow{3}{*}{عدد الطلبة   الموجودين}}       & \multicolumn{3}{c|}{\multirow{3}{*}{عدد اعضاء   الهئية التدريسية}} \\ \cmidrule(lr){6-17}
                               & \multicolumn{4}{c|}{}                                                                        & \multicolumn{3}{c|}{\multirow{2}{*}{الاول   المتوسط}}                                  & \multicolumn{9}{c|}{الرابع   الاعدادي}                                                                                                                                                                                                      & \multicolumn{3}{c|}{}                                              & \multicolumn{3}{c|}{}                                              \\ \cmidrule(lr){9-17}
                               & \multicolumn{4}{c|}{}                                                                        & \multicolumn{3}{c|}{}                                                                  & \multicolumn{2}{c|}{العلمي}                             & \multicolumn{2}{c|}{الادبي}                           & \multicolumn{2}{c|}{الفنون}                           & \multicolumn{3}{c|}{المجموع}                                      & \multicolumn{3}{c|}{}                                              & \multicolumn{3}{c|}{}                                              \\ \cmidrule(l){2-23} 
                               & \multicolumn{1}{c|}{بنون} & \multicolumn{1}{c|}{بنات} & \multicolumn{1}{c|}{مختلط} & المجموع & \multicolumn{1}{c|}{بنون}  & \multicolumn{1}{c|}{بنات}  & \multicolumn{1}{c|}{المجموع} & \multicolumn{1}{c|}{بنون}  & \multicolumn{1}{c|}{بنات}  & \multicolumn{1}{c|}{بنون} & \multicolumn{1}{c|}{بنات} & \multicolumn{1}{c|}{بنون} & \multicolumn{1}{c|}{بنات} & \multicolumn{1}{c|}{بنون}  & \multicolumn{1}{c|}{بنات}  & المجموع & \multicolumn{1}{c|}{بنون}  & \multicolumn{1}{c|}{بنات}   & المجموع & \multicolumn{1}{c|}{ذكور}  & \multicolumn{1}{c|}{اناث}  & المجموع  \\ \midrule
حضر                            & \multicolumn{1}{c|}{160}  & \multicolumn{1}{c|}{168}  & \multicolumn{1}{c|}{3}     & 331     & \multicolumn{1}{c|}{15343} & \multicolumn{1}{c|}{15799} & \multicolumn{1}{c|}{31142}   & \multicolumn{1}{c|}{9843}  & \multicolumn{1}{c|}{14193} & \multicolumn{1}{c|}{956}  & \multicolumn{1}{c|}{1006} & \multicolumn{1}{c|}{0}    & \multicolumn{1}{c|}{0}    & \multicolumn{1}{c|}{10799} & \multicolumn{1}{c|}{15199} & 25998   & \multicolumn{1}{c|}{74150} & \multicolumn{1}{c|}{86965}  & 161115  & \multicolumn{1}{c|}{2833}  & \multicolumn{1}{c|}{5714}  & 8547     \\ \midrule
ريف                            & \multicolumn{1}{c|}{34}   & \multicolumn{1}{c|}{34}   & \multicolumn{1}{c|}{30}    & 98      & \multicolumn{1}{c|}{4710}  & \multicolumn{1}{c|}{4170}  & \multicolumn{1}{c|}{8880}    & \multicolumn{1}{c|}{1909}  & \multicolumn{1}{c|}{2255}  & \multicolumn{1}{c|}{129}  & \multicolumn{1}{c|}{77}   & \multicolumn{1}{c|}{0}    & \multicolumn{1}{c|}{0}    & \multicolumn{1}{c|}{2038}  & \multicolumn{1}{c|}{2332}  & 4370    & \multicolumn{1}{c|}{16094} & \multicolumn{1}{c|}{16483}  & 32577   & \multicolumn{1}{c|}{1470}  & \multicolumn{1}{c|}{2305}  & 3775     \\ \midrule
المجموع                        & \multicolumn{1}{c|}{194}  & \multicolumn{1}{c|}{202}  & \multicolumn{1}{c|}{33}    & 429     & \multicolumn{1}{c|}{20053} & \multicolumn{1}{c|}{19969} & \multicolumn{1}{c|}{40022}   & \multicolumn{1}{c|}{11752} & \multicolumn{1}{c|}{16448} & \multicolumn{1}{c|}{1085} & \multicolumn{1}{c|}{1083} & \multicolumn{1}{c|}{0}    & \multicolumn{1}{c|}{0}    & \multicolumn{1}{c|}{12837} & \multicolumn{1}{c|}{17531} & 30368   & \multicolumn{1}{c|}{90244} & \multicolumn{1}{c|}{103448} & 193692  & \multicolumn{1}{c|}{4303}  & \multicolumn{1}{c|}{8019}  & 12322    \\ \bottomrule
\end{tabular}
}
\end{table}