---
title: ""
documentclass: article
output:
  pdf_document:
    latex_engine: xelatex
    number_sections: true
    includes:
      in_header: models/header.tex
---

```{r, include=FALSE}
#tinytex::uninstall_tinytex()
#tinytex::install_tinytex(force = TRUE)

options(knitr.duplicate.label = "allow")

library(httr)
library(readxl)
library(dplyr)

# رابط ملف البيانات
url <- "https://kf.kobotoolbox.org/api/v2/assets/aycXgGj28xx2kp266wNKY9/export-settings/esiBoLNm45SQnB55UZCAmNq/data.xlsx"

# رمز الوصول
my_token <- "5d24ece551cba75bfe9278bff0b4d482bc266b75"

# اسم ومكان حفظ الملف (داخل مجلد العمل)
file_path <- "data.xlsx"

# تنزيل الملف وحفظه
GET(
  url,
  write_disk(file_path, overwrite = TRUE),
  add_headers(Authorization = paste("Token", my_token))
)

# قراءة الملف
df <- read_excel(file_path)
df_original <- df

# دالة تحويل الأرقام الإنجليزية إلى العربية
ad <- function(x){
  chartr("0123456789", "٠١٢٣٤٥٦٧٨٩", as.character(x))
}

ay <- "2026/2025"
by <- "2027/2026"

```

<!--
```{=latex}
\input{models//cover.tex}
```



```{=latex}
\Large
\tableofcontents
\newpage
\section{رياض الاطفال}
\subsection{التعليم الحكومي}
```
```{r, include=FALSE}
df <- df_original %>%filter(q18 == 1, q4 == 1)
```


```{r, child='file//kg//table1.Rmd'}
```
```{r, child='file//kg//table2.Rmd'}
```
```{r, child='file//kg//table3.Rmd'}
```
```{r, child='file//kg//table4.Rmd'}
```
```{r, child='file//kg//table5.Rmd'}
```
```{r, child='file//kg//table6.Rmd'}
```
```{r, child='file//kg//table7.Rmd'}
```
```{r, child='file//kg//table8.Rmd'}
```
```{r, child='file//kg//table9.Rmd'}
```


```{=latex}
\newpage
\subsection{التعليم الاهلي}
\setcounter{table}{0}
```
```{r, include=FALSE}
df <- df_original %>%filter(q18 == 2, q4 == 1)
```
```{r, child='file//kg//table1.Rmd'}
```
```{r, child='file//kg//table2.Rmd'}
```
```{r, child='file//kg//table3.Rmd'}
```
```{r, child='file//kg//table4.Rmd'}
```
```{r, child='file//kg//table5.Rmd'}
```
```{r, child='file//kg//table6.Rmd'}
```
```{r, child='file//kg//table7.Rmd'}
```
```{r, child='file//kg//table8.Rmd'}
```
```{r, child='file//kg//table9.Rmd'}
```
-->

```{=latex}
\newpage
\section{الابتدائي}
\subsection{التعليم الحكومي}
\setcounter{table}{0}
```
```{r, include=FALSE}

url <- "https://kf.kobotoolbox.org/api/v2/assets/agxT4dyzqAc47Q8wiqqTQ4/export-settings/esCqpVseFBDzpgNMxFFzcnQ/data.xlsx"
tf <- tempfile(fileext = ".xlsx")

my_token <- "5d24ece551cba75bfe9278bff0b4d482bc266b75"

GET(url, 
    write_disk(tf, overwrite = TRUE), 
    add_headers(Authorization = paste("Token", my_token)))


df <- read_excel(tf)
df_original <- df


```
```{r, include=FALSE}
df <- df_original %>%filter(ownership == 1, sch_class == 1)
```

```{r, child='file//pri//table1.Rmd'}
```
