```{r table_v1b_2, include=FALSE}

c11 <- nrow(df[which(df$q6 == "1" &df$q4 == "4"),])
c21 <- sum(as.numeric(df$app21_11a1_4), na.rm = TRUE)
c31 <- sum(as.numeric(df$app21_11a1_6), na.rm = TRUE)
c41 <- sum(as.numeric(df$app21_11a1_8), na.rm = TRUE)
c51 <- sum(as.numeric(df$app21_11a1_10), na.rm = TRUE)
c61 <- sum(as.numeric(df$app21_11a1_12), na.rm = TRUE)
c71 <- sum(as.numeric(df$app21_11a1_14), na.rm = TRUE)


```

\begin{table}[H]
\centering
\caption{عدد التلامذة حسب المرحلة والجنس والعمر }
\begin{tabular}{@{}|c|cc|cc|cc|cc|ccc|@{}}
\toprule
\multirow{2}{*}{\textbf{الاعمار بالسنين}} & \multicolumn{2}{c|}{\textbf{المرحلة الاولى}}       & \multicolumn{2}{c|}{\textbf{المرحلة الثانية}}      & \multicolumn{2}{c|}{\textbf{المرحلة الثالثة}}      & \multicolumn{2}{c|}{\textbf{المرحلة الرابعة}}      & \multicolumn{3}{c|}{\textbf{المجموع الكلي}}                                                \\ \cmidrule(l){2-12} 
                                          & \multicolumn{1}{c|}{\textbf{بنون}} & \textbf{بنات} & \multicolumn{1}{c|}{\textbf{بنون}} & \textbf{بنات} & \multicolumn{1}{c|}{\textbf{بنون}} & \textbf{بنات} & \multicolumn{1}{c|}{\textbf{بنون}} & \textbf{بنات} & \multicolumn{1}{c|}{\textbf{بنون}} & \multicolumn{1}{c|}{\textbf{بنات}} & \textbf{المجموع} \\ \midrule
\textbf{10}                               & \multicolumn{1}{c|}{}              &               & \multicolumn{1}{c|}{}              &               & \multicolumn{1}{c|}{}              &               & \multicolumn{1}{c|}{}              &               & \multicolumn{1}{c|}{}              & \multicolumn{1}{c|}{}              &                  \\ \midrule
\textbf{11}                               & \multicolumn{1}{c|}{}              &               & \multicolumn{1}{c|}{}              &               & \multicolumn{1}{c|}{}              &               & \multicolumn{1}{c|}{}              &               & \multicolumn{1}{c|}{}              & \multicolumn{1}{c|}{}              &                  \\ \midrule
\textbf{12}                               & \multicolumn{1}{c|}{}              &               & \multicolumn{1}{c|}{}              &               & \multicolumn{1}{c|}{}              &               & \multicolumn{1}{c|}{}              &               & \multicolumn{1}{c|}{}              & \multicolumn{1}{c|}{}              &                  \\ \midrule
\textbf{13}                               & \multicolumn{1}{c|}{}              &               & \multicolumn{1}{c|}{}              &               & \multicolumn{1}{c|}{}              &               & \multicolumn{1}{c|}{}              &               & \multicolumn{1}{c|}{}              & \multicolumn{1}{c|}{}              &                  \\ \midrule
\textbf{14}                               & \multicolumn{1}{c|}{}              &               & \multicolumn{1}{c|}{}              &               & \multicolumn{1}{c|}{}              &               & \multicolumn{1}{c|}{}              &               & \multicolumn{1}{c|}{}              & \multicolumn{1}{c|}{}              &                  \\ \midrule
\textbf{15}                               & \multicolumn{1}{c|}{}              &               & \multicolumn{1}{c|}{}              &               & \multicolumn{1}{c|}{}              &               & \multicolumn{1}{c|}{}              &               & \multicolumn{1}{c|}{}              & \multicolumn{1}{c|}{}              &                  \\ \midrule
\textbf{المجموع}                          & \multicolumn{1}{c|}{}              &               & \multicolumn{1}{c|}{}              &               & \multicolumn{1}{c|}{}              &               & \multicolumn{1}{c|}{}              &               & \multicolumn{1}{c|}{}              & \multicolumn{1}{c|}{}              &                  \\ \bottomrule
\end{tabular}
\end{table}