```{r table_v1b_3, include=FALSE}


c11 <- nrow(df[which(df$q6 == "1" &df$q4 == "4"),])
c21 <- sum(as.numeric(df$app21_11a1_4), na.rm = TRUE)
c31 <- sum(as.numeric(df$app21_11a1_6), na.rm = TRUE)
c41 <- sum(as.numeric(df$app21_11a1_8), na.rm = TRUE)
c51 <- sum(as.numeric(df$app21_11a1_10), na.rm = TRUE)
c61 <- sum(as.numeric(df$app21_11a1_12), na.rm = TRUE)
c71 <- sum(as.numeric(df$app21_11a1_14), na.rm = TRUE)


```

\begin{table}[H]
\centering
\caption{التاركون والناجحون والراسبون }
\begin{tabular}{@{}|c|ccc|ccc|ccccccccc|@{}}
\toprule
\multirow{3}{*}{\textbf{المرحلة}} & \multicolumn{3}{c|}{\textbf{\begin{tabular}[c]{@{}c@{}}عدد التلامذة التاركون حسب الصف\\ والجنس للعام الدراسي `r by`\end{tabular}}}            & \multicolumn{3}{c|}{\textbf{\begin{tabular}[c]{@{}c@{}}عدد التلامذة الناجحين للعام \\ الدراسي `r ay` حسب الصف والجنس\end{tabular}}}           & \multicolumn{9}{c|}{\textbf{\begin{tabular}[c]{@{}c@{}}عدد التلامذة الراسبين حسب اسباب الرسوب\\ والصف والجنس للعام الدراسي `r ay`\end{tabular}}}                                                                                                                                                                         \\ \cmidrule(l){2-16} 
                                  & \multicolumn{1}{C{1.3cm}|}{\multirow{2}{*}{\textbf{بنين}}} & \multicolumn{1}{C{1.3cm}|}{\multirow{2}{*}{\textbf{بنات}}} & \multirow{2}{*}{\textbf{المجموع}} & \multicolumn{1}{C{1.3cm}|}{\multirow{2}{*}{\textbf{بنين}}} & \multicolumn{1}{C{1.3cm}|}{\multirow{2}{*}{\textbf{بنات}}} & \multirow{2}{*}{\textbf{المجموع}} & \multicolumn{2}{c|}{\textbf{الفشل في الامتحان}}                         & \multicolumn{2}{c|}{\textbf{تجاوز ايام الغياب}}                         & \multicolumn{2}{c|}{\textbf{أسباب أخرى}}                                & \multicolumn{3}{c|}{\textbf{المجموع}}                                                      \\ \cmidrule(l){8-16} 
                                  & \multicolumn{1}{c|}{}                               & \multicolumn{1}{c|}{}                               &                                   & \multicolumn{1}{c|}{}                               & \multicolumn{1}{c|}{}                               &                                   & \multicolumn{1}{c|}{\textbf{بنون}} & \multicolumn{1}{c|}{\textbf{بنات}} & \multicolumn{1}{c|}{\textbf{بنون}} & \multicolumn{1}{c|}{\textbf{بنات}} & \multicolumn{1}{c|}{\textbf{بنون}} & \multicolumn{1}{c|}{\textbf{بنات}} & \multicolumn{1}{c|}{\textbf{بنون}} & \multicolumn{1}{c|}{\textbf{بنات}} & \textbf{المجموع} \\ \midrule
\textbf{الاولى}                   & \multicolumn{1}{c|}{}                               & \multicolumn{1}{c|}{}                               &                                   & \multicolumn{1}{c|}{}                               & \multicolumn{1}{c|}{}                               &                                   & \multicolumn{1}{c|}{}              & \multicolumn{1}{c|}{}              & \multicolumn{1}{c|}{}              & \multicolumn{1}{c|}{}              & \multicolumn{1}{c|}{}              & \multicolumn{1}{c|}{}              & \multicolumn{1}{c|}{}              & \multicolumn{1}{c|}{}              &                  \\ \midrule
\textbf{الثانية}                  & \multicolumn{1}{c|}{}                               & \multicolumn{1}{c|}{}                               &                                   & \multicolumn{1}{c|}{}                               & \multicolumn{1}{c|}{}                               &                                   & \multicolumn{1}{c|}{}              & \multicolumn{1}{c|}{}              & \multicolumn{1}{c|}{}              & \multicolumn{1}{c|}{}              & \multicolumn{1}{c|}{}              & \multicolumn{1}{c|}{}              & \multicolumn{1}{c|}{}              & \multicolumn{1}{c|}{}              &                  \\ \midrule
\textbf{الثالثة}                  & \multicolumn{1}{c|}{}                               & \multicolumn{1}{c|}{}                               &                                   & \multicolumn{1}{c|}{}                               & \multicolumn{1}{c|}{}                               &                                   & \multicolumn{1}{c|}{}              & \multicolumn{1}{c|}{}              & \multicolumn{1}{c|}{}              & \multicolumn{1}{c|}{}              & \multicolumn{1}{c|}{}              & \multicolumn{1}{c|}{}              & \multicolumn{1}{c|}{}              & \multicolumn{1}{c|}{}              &                  \\ \midrule
\textbf{المجموع}                  & \multicolumn{1}{c|}{}                               & \multicolumn{1}{c|}{}                               &                                   & \multicolumn{1}{c|}{}                               & \multicolumn{1}{c|}{}                               &                                   & \multicolumn{1}{c|}{}              & \multicolumn{1}{c|}{}              & \multicolumn{1}{c|}{}              & \multicolumn{1}{c|}{}              & \multicolumn{1}{c|}{}              & \multicolumn{1}{c|}{}              & \multicolumn{1}{c|}{}              & \multicolumn{1}{c|}{}              &                  \\ \bottomrule
\end{tabular}
\end{table}