```{r table_v1c_1, include=FALSE}

c11 <- " النجف / الكوفة / المناذرة / المشخاب"
c21 <- ""
c31 <- nrow(df)
c41 <- nrow(df[which(df$q22 == "1"),])
c51 <- nrow(df[which(df$q22 == "2"),])
c61 <- nrow(df[which(df$q6 == "1"),])
c71 <- nrow(df[which(df$q6 == "2"),])
c81 <- nrow(df[which(df$q20 == "1"),])
c91 <- nrow(df[which(df$q20 == "2"),])
c101 <- nrow(df[which(df$q20 == "3"),])
c111 <- sum(as.numeric(df$form6_8a_18), na.rm = TRUE)
c121 <- sum(as.numeric(df$form6_8a_19), na.rm = TRUE)
c131 <- sum(as.numeric(df$form6_8a_20), na.rm = TRUE)
```


\begin{table}[H]
\centering
\begin{tabular}{@{}cccccccccccc@{}}
\cmidrule(lr){2-2} \cmidrule(lr){7-7} \cmidrule(l){12-12}
\multicolumn{1}{c|}{اسم المدرسة:} & \multicolumn{1}{c|}{محافظة النجف الاشرف} &  &  &  & \multicolumn{1}{c|}{القضاء:}  & \multicolumn{1}{c|}{`r c11`} &  &  &  & \multicolumn{1}{c|}{الناحية:} & \multicolumn{1}{c|}{`r c21`} \\ \cmidrule(lr){2-2} \cmidrule(lr){7-7} \cmidrule(l){12-12} 
                                  &                                          &  &  &  &                               &                              &  &  &  &                               &                              \\ \cmidrule(lr){2-2} \cmidrule(lr){7-7} \cmidrule(l){12-12} 
\multicolumn{1}{c|}{عدد المدارس:} & \multicolumn{1}{c|}{`r c31`}             &  &  &  & \multicolumn{1}{c|}{الاصلية:} & \multicolumn{1}{c|}{`r c41`} &  &  &  & \multicolumn{1}{c|}{الضيف:}   & \multicolumn{1}{c|}{`r c51`} \\ \cmidrule(lr){2-2} \cmidrule(lr){7-7} \cmidrule(l){12-12} 
\end{tabular}
\end{table}


\begin{table}[H]
\centering
\begin{tabular}{@{}|cc|cc|ccc|cc|ccc|@{}}
\cmidrule(r){1-2} \cmidrule(lr){5-7} \cmidrule(l){10-12}
\multicolumn{2}{|c|}{الموقع البيئي للمدرسة} &  &  & \multicolumn{3}{c|}{جنس المدرسة}                                       &  &  & \multicolumn{3}{c|}{عدد اعضاء الهيئة التعليمية}                          \\ \cmidrule(r){1-2} \cmidrule(lr){5-7} \cmidrule(l){10-12} 
\multicolumn{1}{|c|}{حضر}       & ريف       &  &  & \multicolumn{1}{c|}{بنون}    & \multicolumn{1}{c|}{بنات}    & مختلط    &  &  & \multicolumn{1}{c|}{ذكور}     & \multicolumn{1}{c|}{اناث}     & المجموع  \\ \cmidrule(r){1-2} \cmidrule(lr){5-7} \cmidrule(l){10-12} 
\multicolumn{1}{|c|}{`r c61`}   & `r c71`   &  &  & \multicolumn{1}{c|}{`r c81`} & \multicolumn{1}{c|}{`r c91`} & `r c101` &  &  & \multicolumn{1}{c|}{`r c111`} & \multicolumn{1}{c|}{`r c121`} & `r c131` \\ \cmidrule(r){1-2} \cmidrule(lr){5-7} \cmidrule(l){10-12} 
\end{tabular}
\end{table}
