```{r table_v2_1, include=FALSE}

c11 <- nrow(df[which(df$q6 == "1" &df$q20 == "1"),])
c12 <- nrow(df[which(df$q6 == "2" &df$q20 == "1"),])
c13 <- c11 + c12

c21 <- nrow(df[which(df$q6 == "1" &df$q20 == "2"),])
c22 <- nrow(df[which(df$q6 == "2" &df$q20 == "2"),])
c23 <- c21 + c22

c31 <- nrow(df[which(df$q6 == "1" &df$q20 == "3"),])
c32 <- nrow(df[which(df$q6 == "2" &df$q20 == "3"),])
c33 <- c31 + c32 

c41 <- c11 + c21 + c31
c42 <- c12 + c22 + c32
c43 <- c41 + c42 

c51 <- sum(df$table25a_32[df$q6 == "1"], na.rm = TRUE)
c52 <- sum(df$table25a_32[df$q6 == "2"], na.rm = TRUE)
c53 <- c51 + c52

c61 <- sum(df$table25a_33[df$q6 == "1"], na.rm = TRUE)
c62 <- sum(df$table25a_33[df$q6 == "2"], na.rm = TRUE)
c63 <- c61 + c62

c71 <- c51 + c61
c72 <- c52 + c62
c73 <- c71 + c72



```

\begin{table}[H]
\centering
\caption{عدد المدارس والطلبة الموجودين وعدد اعضاء الهيئة التدريسية واستقلالية المدرسة ومدارس الفتح الجديد (الصباحي والمسائي)}
\resizebox{\textwidth}{!}{%
\begin{tabular}{@{}|c|cccc|ccc|ccc|ccc|cccc|cccc|cc|@{}}
\toprule
\multirow{2}{*}{درجة المدرسة} & \multicolumn{4}{c|}{عدد المدارس}                                                             & \multicolumn{3}{c|}{عدد الطلبة   الموجودين}                        & \multicolumn{3}{c|}{عدد اعضاء   الهئية التدريسية}               & \multicolumn{3}{c|}{استقلالية المدرسة}                          & \multicolumn{4}{c|}{عدد المدارس   حسب نوع الدوام}                                                      & \multicolumn{4}{c|}{عدد الشعب}                                                               & \multicolumn{2}{c|}{مدارس الفتح الجديد} \\ \cmidrule(l){2-24} 
                              & \multicolumn{1}{c|}{بنون} & \multicolumn{1}{c|}{بنات} & \multicolumn{1}{c|}{مختلط} & المجموع & \multicolumn{1}{c|}{بنون}  & \multicolumn{1}{c|}{بنات}   & المجموع & \multicolumn{1}{c|}{ذكور} & \multicolumn{1}{c|}{اناث} & المجموع & \multicolumn{1}{c|}{اصلية} & \multicolumn{1}{c|}{ضيف} & استضافة & \multicolumn{1}{c|}{صباحاً} & \multicolumn{1}{c|}{ظهراً} & \multicolumn{1}{c|}{صباحاً وظهراً} & مساءاً & \multicolumn{1}{c|}{بنون} & \multicolumn{1}{c|}{بنات} & \multicolumn{1}{c|}{مختلط} & المجموع & \multicolumn{1}{c|}{نعم}      & كلا     \\ \midrule
متوسطة                        & \multicolumn{1}{c|}{98}   & \multicolumn{1}{c|}{69}   & \multicolumn{1}{c|}{13}    & 180     & \multicolumn{1}{c|}{38941} & \multicolumn{1}{c|}{31094}  & 70035   & \multicolumn{1}{c|}{1489} & \multicolumn{1}{c|}{3124} & 4613    & \multicolumn{1}{c|}{98}    & \multicolumn{1}{c|}{82}  & 0       & \multicolumn{1}{c|}{98}     & \multicolumn{1}{c|}{76}    & \multicolumn{1}{c|}{0}             & 6      & \multicolumn{1}{c|}{1067} & \multicolumn{1}{c|}{829}  & \multicolumn{1}{c|}{11}    & 1907    & \multicolumn{1}{c|}{9}        & 171     \\ \midrule
اعدادي                        & \multicolumn{1}{c|}{47}   & \multicolumn{1}{c|}{46}   & \multicolumn{1}{c|}{2}     & 95      & \multicolumn{1}{c|}{25189} & \multicolumn{1}{c|}{26269}  & 51458   & \multicolumn{1}{c|}{1265} & \multicolumn{1}{c|}{1305} & 2570    & \multicolumn{1}{c|}{65}    & \multicolumn{1}{c|}{30}  & 0       & \multicolumn{1}{c|}{63}     & \multicolumn{1}{c|}{28}    & \multicolumn{1}{c|}{2}             & 2      & \multicolumn{1}{c|}{614}  & \multicolumn{1}{c|}{589}  & \multicolumn{1}{c|}{3}     & 1206    & \multicolumn{1}{c|}{6}        & 89      \\ \midrule
ثانوي                         & \multicolumn{1}{c|}{49}   & \multicolumn{1}{c|}{87}   & \multicolumn{1}{c|}{18}    & 154     & \multicolumn{1}{c|}{26114} & \multicolumn{1}{c|}{46085}  & 72199   & \multicolumn{1}{c|}{1549} & \multicolumn{1}{c|}{3590} & 5139    & \multicolumn{1}{c|}{82}    & \multicolumn{1}{c|}{72}  & 0       & \multicolumn{1}{c|}{80}     & \multicolumn{1}{c|}{59}    & \multicolumn{1}{c|}{2}             & 13     & \multicolumn{1}{c|}{705}  & \multicolumn{1}{c|}{1163} & \multicolumn{1}{c|}{37}    & 1905    & \multicolumn{1}{c|}{13}       & 141     \\ \midrule
المجموع                       & \multicolumn{1}{c|}{194}  & \multicolumn{1}{c|}{202}  & \multicolumn{1}{c|}{33}    & 429     & \multicolumn{1}{c|}{90244} & \multicolumn{1}{c|}{103448} & 193692  & \multicolumn{1}{c|}{4303} & \multicolumn{1}{c|}{8019} & 12322   & \multicolumn{1}{c|}{245}   & \multicolumn{1}{c|}{184} & 0       & \multicolumn{1}{c|}{241}    & \multicolumn{1}{c|}{163}   & \multicolumn{1}{c|}{4}             & 21     & \multicolumn{1}{c|}{2386} & \multicolumn{1}{c|}{2581} & \multicolumn{1}{c|}{51}    & 5018    & \multicolumn{1}{c|}{28}       & 401     \\ \bottomrule
\end{tabular}
}
\end{table}