```{r table_v2_3, include=FALSE}

c11 <- nrow(df[which(df$q6 == "1" &df$q20 == "1"),])
c12 <- nrow(df[which(df$q6 == "2" &df$q20 == "1"),])
c13 <- c11 + c12

c21 <- nrow(df[which(df$q6 == "1" &df$q20 == "2"),])
c22 <- nrow(df[which(df$q6 == "2" &df$q20 == "2"),])
c23 <- c21 + c22

c31 <- nrow(df[which(df$q6 == "1" &df$q20 == "3"),])
c32 <- nrow(df[which(df$q6 == "2" &df$q20 == "3"),])
c33 <- c31 + c32 

c41 <- c11 + c21 + c31
c42 <- c12 + c22 + c32
c43 <- c41 + c42 

c51 <- sum(df$table25a_32[df$q6 == "1"], na.rm = TRUE)
c52 <- sum(df$table25a_32[df$q6 == "2"], na.rm = TRUE)
c53 <- c51 + c52

c61 <- sum(df$table25a_33[df$q6 == "1"], na.rm = TRUE)
c62 <- sum(df$table25a_33[df$q6 == "2"], na.rm = TRUE)
c63 <- c61 + c62

c71 <- c51 + c61
c72 <- c52 + c62
c73 <- c71 + c72



```

\begin{table}[H]
\centering
\caption{عدد الطلبة المقبولين الجدد في الاول المتوسط والرابع العلمي والادبي حسب العمر والجنس (الصباحي والمسائي)}
\begin{tabular}{@{}|c|ccc|ccccccccc|@{}}
\toprule
\multirow{3}{*}{العمر} & \multicolumn{3}{c|}{الطلبة الجدد   في الاول المتوسط}                                                               & \multicolumn{9}{c|}{الطلبة الجدد في الرابع الاعدادي}                                                                                                                                                                                        \\ \cmidrule(l){2-13} 
                       & \multicolumn{1}{c|}{\multirow{2}{*}{بنون}} & \multicolumn{1}{c|}{\multirow{2}{*}{بنات}} & \multirow{2}{*}{المجموع} & \multicolumn{2}{c|}{الرابع العلمي}                      & \multicolumn{2}{c|}{الرابع الادبي}                    & \multicolumn{2}{c|}{الرابع الفنون}                    & \multicolumn{3}{c|}{المجموع}                                      \\ \cmidrule(l){5-13} 
                       & \multicolumn{1}{c|}{}                      & \multicolumn{1}{c|}{}                      &                          & \multicolumn{1}{c|}{بنون}  & \multicolumn{1}{c|}{بنات}  & \multicolumn{1}{c|}{بنون} & \multicolumn{1}{c|}{بنات} & \multicolumn{1}{c|}{بنون} & \multicolumn{1}{c|}{بنات} & \multicolumn{1}{c|}{بنون}  & \multicolumn{1}{c|}{بنات}  & المجموع \\ \midrule
عمر 12                 & \multicolumn{1}{c|}{6731}                  & \multicolumn{1}{c|}{8496}                  & 15227                    & \multicolumn{1}{c|}{}      & \multicolumn{1}{c|}{}      & \multicolumn{1}{c|}{}     & \multicolumn{1}{c|}{}     & \multicolumn{1}{c|}{}     & \multicolumn{1}{c|}{}     & \multicolumn{1}{c|}{}      & \multicolumn{1}{c|}{}      &         \\ \midrule
عمر   13               & \multicolumn{1}{c|}{5928}                  & \multicolumn{1}{c|}{6423}                  & 12351                    & \multicolumn{1}{c|}{}      & \multicolumn{1}{c|}{}      & \multicolumn{1}{c|}{}     & \multicolumn{1}{c|}{}     & \multicolumn{1}{c|}{}     & \multicolumn{1}{c|}{}     & \multicolumn{1}{c|}{}      & \multicolumn{1}{c|}{}      &         \\ \midrule
عمر   14               & \multicolumn{1}{c|}{3533}                  & \multicolumn{1}{c|}{2714}                  & 6247                     & \multicolumn{1}{c|}{}      & \multicolumn{1}{c|}{}      & \multicolumn{1}{c|}{}     & \multicolumn{1}{c|}{}     & \multicolumn{1}{c|}{}     & \multicolumn{1}{c|}{}     & \multicolumn{1}{c|}{}      & \multicolumn{1}{c|}{}      &         \\ \midrule
عمر   15               & \multicolumn{1}{c|}{2077}                  & \multicolumn{1}{c|}{1456}                  & 3533                     & \multicolumn{1}{c|}{4396}  & \multicolumn{1}{c|}{7148}  & \multicolumn{1}{c|}{333}  & \multicolumn{1}{c|}{350}  & \multicolumn{1}{c|}{0}    & \multicolumn{1}{c|}{0}    & \multicolumn{1}{c|}{4729}  & \multicolumn{1}{c|}{7498}  & 12227   \\ \midrule
عمر   16               & \multicolumn{1}{c|}{1784}                  & \multicolumn{1}{c|}{880}                   & 2664                     & \multicolumn{1}{c|}{3893}  & \multicolumn{1}{c|}{5042}  & \multicolumn{1}{c|}{259}  & \multicolumn{1}{c|}{301}  & \multicolumn{1}{c|}{0}    & \multicolumn{1}{c|}{0}    & \multicolumn{1}{c|}{4152}  & \multicolumn{1}{c|}{5343}  & 9495    \\ \midrule
عمر   17               & \multicolumn{1}{c|}{}                      & \multicolumn{1}{c|}{}                      &                          & \multicolumn{1}{c|}{1819}  & \multicolumn{1}{c|}{2331}  & \multicolumn{1}{c|}{198}  & \multicolumn{1}{c|}{209}  & \multicolumn{1}{c|}{0}    & \multicolumn{1}{c|}{0}    & \multicolumn{1}{c|}{2017}  & \multicolumn{1}{c|}{2540}  & 4557    \\ \midrule
عمر   18               & \multicolumn{1}{c|}{}                      & \multicolumn{1}{c|}{}                      &                          & \multicolumn{1}{c|}{984}   & \multicolumn{1}{c|}{1246}  & \multicolumn{1}{c|}{138}  & \multicolumn{1}{c|}{129}  & \multicolumn{1}{c|}{0}    & \multicolumn{1}{c|}{0}    & \multicolumn{1}{c|}{1122}  & \multicolumn{1}{c|}{1375}  & 2497    \\ \midrule
عمر   19               & \multicolumn{1}{c|}{}                      & \multicolumn{1}{c|}{}                      &                          & \multicolumn{1}{c|}{660}   & \multicolumn{1}{c|}{681}   & \multicolumn{1}{c|}{157}  & \multicolumn{1}{c|}{94}   & \multicolumn{1}{c|}{0}    & \multicolumn{1}{c|}{0}    & \multicolumn{1}{c|}{817}   & \multicolumn{1}{c|}{775}   & 1592    \\ \midrule
المجموع                & \multicolumn{1}{c|}{20053}                 & \multicolumn{1}{c|}{19969}                 & 40022                    & \multicolumn{1}{c|}{11752} & \multicolumn{1}{c|}{16448} & \multicolumn{1}{c|}{1085} & \multicolumn{1}{c|}{1083} & \multicolumn{1}{c|}{0}    & \multicolumn{1}{c|}{0}    & \multicolumn{1}{c|}{12837} & \multicolumn{1}{c|}{17531} & 30368   \\ \bottomrule
\end{tabular}
\end{table}