```{r table1_2, include=FALSE}
#التعليم الابتدائي النظامي
url <- "https://eu.kobotoolbox.org/api/v2/assets/aXnQNtQ4JkqoZWqiAJgWjb/export-settings/es2DWRs8ATF9X6aQQubQ5pi/data.xlsx"
tf <- tempfile(fileext = ".xlsx")
GET(url, write_disk(tf, overwrite = TRUE))
df <- read_excel(tf)

df <- df %>% filter(q4 == 1 & q4a == 1)

c21 <- nrow(df[which(df$q4 == "1" &df$q4a == "1" &df$q20 == "1"),])
c22 <- nrow(df[which(df$q4 == "1" &df$q4a == "1" &df$q20 == "2"),])
c23 <- nrow(df[which(df$q4 == "1" &df$q4a == "1" &df$q20 == "3"),])
c24 <- "19000"
```

\begin{table}[H]
\centering
\caption{إعداد المدارس الحكومية حسب المراحل الدراسية والتوزيع الإداري (قضاء النجف) للعام الدراسي `r by`}
\begin{tabular}{|c|c|c|c|c|c|c|c|c|c|c|c|c|}
\hline
\textbf{الناحية}                     & \textbf{النوع الاجتماعي} & \textbf{رياض الاطفال} & \textbf{الابتدائية}   & \textbf{اليافعين}     & \textbf{المتوسط}      & \textbf{الاعدادي}     & \textbf{الثانوي}      & \textbf{مجموع الثانوي} & \textbf{المعاهد}      & \textbf{المهني}       & \textbf{المسرع}       & \textbf{المجموع}      \\ \hline
\multirow{4}{*}{\textbf{مركز النجف}} & \textbf{بنون}            & \textbf{}             & \textbf{`r c21`}      & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}              & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             \\ \cline{2-13} 
                                     & \textbf{اناث}            & \textbf{}             & \textbf{`r c22`}      & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}              & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             \\ \cline{2-13} 
                                     & \textbf{مختلط}           &                       & \textbf{`r c23`}      &                       &                       &                       &                       &                        &                       &                       &                       &                       \\ \cline{2-13} 
                                     & \textbf{المجموع}         & \textbf{}             & \textbf{`r c24`}      & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}              & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             \\ \hline
\multirow{4}{*}{\textbf{الحيدرية}}   & \textbf{بنون}            & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}              & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             \\ \cline{2-13} 
                                     & \textbf{اناث}            & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}              & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             \\ \cline{2-13} 
                                     & \textbf{مختلط}           &                       &                       &                       &                       &                       &                       &                        &                       &                       &                       &                       \\ \cline{2-13} 
                                     & \textbf{المجموع}         & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}              & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             \\ \hline
\multirow{4}{*}{\textbf{الرضوية}}    & \textbf{بنون}            & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}              & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             \\ \cline{2-13} 
                                     & \textbf{اناث}            & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}              & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             \\ \cline{2-13} 
                                     & \textbf{مختلط}           &                       &                       &                       &                       &                       &                       &                        &                       &                       &                       &                       \\ \cline{2-13} 
                                     & \textbf{المجموع}         & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}              & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             \\ \hline
\multirow{4}{*}{\textbf{الشبكة}}     & \textbf{بنون}            & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}              & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             \\ \cline{2-13} 
                                     & \textbf{اناث}            & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}              & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             \\ \cline{2-13} 
                                     & \textbf{مختلط}           &                       &                       &                       &                       &                       &                       &                        &                       &                       &                       &                       \\ \cline{2-13} 
                                     & \textbf{المجموع}         & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}              & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             \\ \hline
\multirow{4}{*}{\textbf{بانيقيا}}    & \textbf{بنون}            & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}              & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             \\ \cline{2-13} 
                                     & \textbf{اناث}            & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}              & \textbf{}             & \textbf{}             & \textbf{}             & \textbf{}             \\ \cline{2-13} 
                                     & \textbf{مختلط}           &                       &                       &                       &                       &                       &                       &                        &                       &                       &                       &                       \\ \cline{2-13} 
                                     & \textbf{المجموع}         &                       &                       &                       &                       &                       &                       &                        &                       &                       &                       &                       \\ \hline
\multirow{4}{*}{\textbf{المجموع}}    & \textbf{بنون}            &                       &                       &                       &                       &                       &                       &                        &                       &                       &                       &                       \\ \cline{2-13} 
                                     & \textbf{اناث}            &                       &                       &                       &                       &                       &                       &                        &                       &                       &                       &                       \\ \cline{2-13} 
                                     & \textbf{مختلط}           & \multicolumn{1}{l|}{} & \multicolumn{1}{l|}{} & \multicolumn{1}{l|}{} & \multicolumn{1}{l|}{} & \multicolumn{1}{l|}{} & \multicolumn{1}{l|}{} & \multicolumn{1}{l|}{}  & \multicolumn{1}{l|}{} & \multicolumn{1}{l|}{} & \multicolumn{1}{l|}{} & \multicolumn{1}{l|}{} \\ \cline{2-13} 
                                     & \textbf{المجموع}         & \multicolumn{1}{l|}{} & \multicolumn{1}{l|}{} & \multicolumn{1}{l|}{} & \multicolumn{1}{l|}{} & \multicolumn{1}{l|}{} & \multicolumn{1}{l|}{} & \multicolumn{1}{l|}{}  & \multicolumn{1}{l|}{} & \multicolumn{1}{l|}{} & \multicolumn{1}{l|}{} & \multicolumn{1}{l|}{} \\ \hline
\end{tabular}
\end{table}
