```{r table_v1b_7, include=FALSE}

c11 <- sum(as.numeric(df$form6_4a_2), na.rm = TRUE)
c21 <- sum(as.numeric(df$form6_4a_3), na.rm = TRUE)
c31 <- sum(as.numeric(df$form6_4a_4), na.rm = TRUE)

c12 <- sum(as.numeric(df$form6_4a_6), na.rm = TRUE)
c22 <- sum(as.numeric(df$form6_4a_7), na.rm = TRUE)
c32 <- sum(as.numeric(df$form6_4a_8), na.rm = TRUE)

c13 <- sum(as.numeric(df$form6_4a_10), na.rm = TRUE)
c23 <- sum(as.numeric(df$form6_4a_11), na.rm = TRUE)
c33 <- sum(as.numeric(df$form6_4a_12), na.rm = TRUE)

c14 <- sum(as.numeric(df$form6_4a_14), na.rm = TRUE)
c24 <- sum(as.numeric(df$form6_4a_15), na.rm = TRUE)
c34 <- sum(as.numeric(df$form6_4a_16), na.rm = TRUE)

c15 <- sum(as.numeric(df$form6_4a_18), na.rm = TRUE)
c25 <- sum(as.numeric(df$form6_4a_19), na.rm = TRUE)
c35 <- sum(as.numeric(df$form6_4a_20), na.rm = TRUE)

c16 <- sum(as.numeric(df$form6_4a_22), na.rm = TRUE)
c26 <- sum(as.numeric(df$form6_4a_23), na.rm = TRUE)
c36 <- sum(as.numeric(df$form6_4a_24), na.rm = TRUE)

c17 <- "///"
c27 <- sum(as.numeric(df$form6_4a_27), na.rm = TRUE)
c37 <- sum(as.numeric(df$form6_4a_28), na.rm = TRUE)

c18 <- sum(as.numeric(df$form6_4a_30), na.rm = TRUE)
c28 <- sum(as.numeric(df$form6_4a_31), na.rm = TRUE)
c38 <- sum(as.numeric(df$form6_4a_32), na.rm = TRUE)

c19 <- sum(as.numeric(df$form6_4a_34), na.rm = TRUE)
c29 <- sum(as.numeric(df$form6_4a_35), na.rm = TRUE)
c39 <- sum(as.numeric(df$form6_4a_36), na.rm = TRUE)

c110 <- sum(as.numeric(df$form6_4a_38), na.rm = TRUE)
c210 <- sum(as.numeric(df$form6_4a_39), na.rm = TRUE)
c310 <- sum(as.numeric(df$form6_4a_40), na.rm = TRUE)

#########################################################

v11 <- sum(as.numeric(df$form6_9a_2), na.rm = TRUE)
v12 <- sum(as.numeric(df$form6_9a_3), na.rm = TRUE)
v13 <- sum(as.numeric(df$form6_9a_4), na.rm = TRUE)


```


\begin{table}[H]
\centering
% ملاحظة: تم وضع الـ label الأول داخل الميني بيج الأولى لمنع التداخل
\begin{minipage}[t]{0.48\textwidth}
\centering
\caption{عدد اعضاء الهيئة التعليمية حسب الحالة الوظيفية}
\label{tab:status} % اسم فريد للجدول الأول
\begin{tabular}{@{}|ccl|c|c|c|@{}}
\toprule
\multicolumn{3}{|c|}{الحالة الوظيفية} & ذكور & اناث & المجموع \\ \midrule
\multicolumn{3}{|c|}{داخل قوة العمل} & `r c11` & `r c21` & `r c31` \\ \midrule
\multicolumn{1}{|c|}{\multirow{8}{*}{خارج قوة العمل}} & \multicolumn{2}{c|}{بعثة او زمالة دراسية} & `r c12` & `r c22` & `r c32` \\ \cmidrule(l){2-6} 
\multicolumn{1}{|c|}{} & \multicolumn{2}{c|}{اجازة دراسية} & `r c13` & `r c23` & `r c33` \\ \cmidrule(l){2-6} 
\multicolumn{1}{|c|}{} & \multicolumn{2}{c|}{اجازة مصاحبة} & `r c14` & `r c24` & `r c34` \\ \cmidrule(l){2-6} 
\multicolumn{1}{|c|}{} & \multicolumn{2}{c|}{اجازة بدون راتب} & `r c15` & `r c25` & `r c35` \\ \cmidrule(l){2-6} 
\multicolumn{1}{|c|}{} & \multicolumn{2}{c|}{اجازة مرضية طويلة} & `r c16` & `r c26` & `r c36` \\ \cmidrule(l){2-6} 
\multicolumn{1}{|c|}{} & \multicolumn{2}{c|}{اجازة امومة} & `r c17` & `r c27` & `r c37` \\ \cmidrule(l){2-6} 
\multicolumn{1}{|c|}{} & \multicolumn{2}{c|}{تنسيب الى جهات اخرى} & `r c18` & `r c28` & `r c38` \\ \cmidrule(l){2-6} 
\multicolumn{1}{|c|}{} & \multicolumn{2}{c|}{5-4 سنوات} & `r c19` & `r c29` & `r c39` \\ \midrule
\multicolumn{3}{|c|}{المجموع الكلي} & `r c110` & `r c210` & `r c310` \\ \bottomrule
\end{tabular}
\end{minipage}
\hfill
\begin{minipage}[t]{0.48\textwidth}
\centering
\caption{عدد اعضاء الهيئة التعليمية المشاركين في الدورات التدريبية}
\label{tab:training} % اسم فريد للجدول الثاني
\begin{tabular}{@{}|cl|cl|@{}}
\toprule
\multicolumn{2}{|c|}{الجنس} & \multicolumn{2}{c|}{عدد المعلمين} \\ \midrule
\multicolumn{2}{|c|}{ذكور} & \multicolumn{2}{c|}{`r v11`} \\ \midrule
\multicolumn{2}{|c|}{اناث} & \multicolumn{2}{c|}{`r v12`} \\ \midrule
\multicolumn{2}{|c|}{المجموع} & \multicolumn{2}{c|}{`r v13`} \\ \bottomrule
\end{tabular}
\end{minipage}
\end{table}

