```{r table_v1b_4, include=FALSE}

c11 <- nrow(df[which(df$q6 == "1" &df$q4 == "4"),])
c21 <- sum(as.numeric(df$app21_11a1_4), na.rm = TRUE)
c31 <- sum(as.numeric(df$app21_11a1_6), na.rm = TRUE)
c41 <- sum(as.numeric(df$app21_11a1_8), na.rm = TRUE)
c51 <- sum(as.numeric(df$app21_11a1_10), na.rm = TRUE)
c61 <- sum(as.numeric(df$app21_11a1_12), na.rm = TRUE)
c71 <- sum(as.numeric(df$app21_11a1_14), na.rm = TRUE)


```

\begin{table}[H]
\centering
\begin{tabular}{@{}|ccc|ccc|ccc|ccc|cccc|@{}}
\toprule
\multicolumn{3}{|c|}{\textbf{المرحلة الاولى}}                                             & \multicolumn{3}{c|}{\textbf{المرحلة الثانية}}                                            & \multicolumn{3}{c|}{\textbf{المرحلة الثالثة}}                                            & \multicolumn{3}{c|}{\textbf{المرحلة الرابعة}}                                            & \multicolumn{4}{c|}{\textbf{المجموع}}                                                                                            \\ \midrule
\multicolumn{1}{|c|}{\textbf{بنون}} & \multicolumn{1}{c|}{\textbf{بنات}} & \textbf{مختلط} & \multicolumn{1}{c|}{\textbf{بنون}} & \multicolumn{1}{c|}{\textbf{بنات}} & \textbf{مختلط} & \multicolumn{1}{c|}{\textbf{بنون}} & \multicolumn{1}{c|}{\textbf{بنات}} & \textbf{مختلط} & \multicolumn{1}{c|}{\textbf{بنون}} & \multicolumn{1}{c|}{\textbf{بنات}} & \textbf{مختلط} & \multicolumn{1}{c|}{\textbf{بنون}} & \multicolumn{1}{c|}{\textbf{بنات}} & \multicolumn{1}{c|}{\textbf{مختلط}} & \textbf{المجموع} \\ \midrule
\multicolumn{1}{|c|}{\textbf{}}     & \multicolumn{1}{c|}{\textbf{}}     & \textbf{}      & \multicolumn{1}{c|}{\textbf{}}     & \multicolumn{1}{c|}{\textbf{}}     & \textbf{}      & \multicolumn{1}{c|}{\textbf{}}     & \multicolumn{1}{c|}{\textbf{}}     & \textbf{}      & \multicolumn{1}{c|}{\textbf{}}     & \multicolumn{1}{c|}{\textbf{}}     & \textbf{}      & \multicolumn{1}{c|}{\textbf{}}     & \multicolumn{1}{c|}{\textbf{}}     & \multicolumn{1}{c|}{\textbf{}}      & \textbf{}        \\ \bottomrule
\end{tabular}
\end{table}
