```{r table_v1c_6, include=FALSE}

###التاركون
c11 <- sum(as.numeric(df$form3_b_7_2), na.rm = TRUE)
c12 <- sum(as.numeric(df$form3_b_7_7), na.rm = TRUE)
c13 <- sum(as.numeric(df$form3_b_7_12), na.rm = TRUE)
c14 <- sum(as.numeric(df$form3_b_7_17), na.rm = TRUE)

c21 <- sum(as.numeric(df$form3_b_7_3), na.rm = TRUE)
c22 <- sum(as.numeric(df$form3_b_7_8), na.rm = TRUE)
c23 <- sum(as.numeric(df$form3_b_7_13), na.rm = TRUE)
c24 <- sum(as.numeric(df$form3_b_7_18), na.rm = TRUE)

c31 <- sum(as.numeric(df$form3_b_7_4), na.rm = TRUE)
c32 <- sum(as.numeric(df$form3_b_7_9), na.rm = TRUE)
c33 <- sum(as.numeric(df$form3_b_7_14), na.rm = TRUE)
c34 <- sum(as.numeric(df$form3_b_7_19), na.rm = TRUE)


###الناجحون
c41 <- sum(as.numeric(df$form3_b_8_2), na.rm = TRUE)
c42 <- sum(as.numeric(df$form3_b_8_7), na.rm = TRUE)
c43 <- sum(as.numeric(df$form3_b_8_12), na.rm = TRUE)
c44 <- sum(as.numeric(df$form3_b_8_17), na.rm = TRUE)

c51 <- sum(as.numeric(df$form3_b_8_3), na.rm = TRUE)
c52 <- sum(as.numeric(df$form3_b_8_8), na.rm = TRUE)
c53 <- sum(as.numeric(df$form3_b_8_13), na.rm = TRUE)
c54 <- sum(as.numeric(df$form3_b_8_18), na.rm = TRUE)

c61 <- sum(as.numeric(df$form3_b_8_4), na.rm = TRUE)
c62 <- sum(as.numeric(df$form3_b_8_9), na.rm = TRUE)
c63 <- sum(as.numeric(df$form3_b_8_14), na.rm = TRUE)
c64 <- sum(as.numeric(df$form3_b_8_19), na.rm = TRUE)


###الفشل في الامتحان
c71 <- sum(as.numeric(df$form3_b_9_2), na.rm = TRUE)
c72 <- sum(as.numeric(df$form3_b_9_7), na.rm = TRUE)
c73 <- sum(as.numeric(df$form3_b_9_12), na.rm = TRUE)
c74 <- sum(as.numeric(df$form3_b_9_17), na.rm = TRUE)

c81 <- sum(as.numeric(df$form3_b_9_3), na.rm = TRUE)
c82 <- sum(as.numeric(df$form3_b_9_8), na.rm = TRUE)
c83 <- sum(as.numeric(df$form3_b_9_13), na.rm = TRUE)
c84 <- sum(as.numeric(df$form3_b_9_18), na.rm = TRUE)


###تجاوز ايام الغياب
c91 <- sum(as.numeric(df$form3_b_10_2), na.rm = TRUE)
c92 <- sum(as.numeric(df$form3_b_10_7), na.rm = TRUE)
c93 <- sum(as.numeric(df$form3_b_10_12), na.rm = TRUE)
c94 <- sum(as.numeric(df$form3_b_10_17), na.rm = TRUE)

c101 <- sum(as.numeric(df$form3_b_10_3), na.rm = TRUE)
c102 <- sum(as.numeric(df$form3_b_10_8), na.rm = TRUE)
c103 <- sum(as.numeric(df$form3_b_10_13), na.rm = TRUE)
c104 <- sum(as.numeric(df$form3_b_10_18), na.rm = TRUE)


###اسباب اخرى
c111 <- sum(as.numeric(df$form3_b_11_2), na.rm = TRUE)
c112 <- sum(as.numeric(df$form3_b_11_7), na.rm = TRUE)
c113 <- sum(as.numeric(df$form3_b_11_12), na.rm = TRUE)
c114 <- sum(as.numeric(df$form3_b_11_17), na.rm = TRUE)

c121 <- sum(as.numeric(df$form3_b_7_3), na.rm = TRUE)
c122 <- sum(as.numeric(df$form3_b_7_8), na.rm = TRUE)
c123 <- sum(as.numeric(df$form3_b_7_13), na.rm = TRUE)
c124 <- sum(as.numeric(df$form3_b_7_18), na.rm = TRUE)


###المجموع
c131 <- c71 + c91 + c111
c132 <- c72 + c92 + c112
c133 <- c73 + c93 + c113
c134 <- c74 + c94 + c114

c141 <- c81 + c101 + c121
c142 <- c82 + c102 + c122
c143 <- c83 + c103 + c123
c144 <- c84 + c104 + c124

c151 <- c131 + c141
c152 <- c132 + c142
c153 <- c133 + c143
c154 <- c134 + c144



```

\begin{table}[H]
\centering
\caption{التاركون والناجحون والراسبون }
\begin{tabular}{@{}|c|ccc|ccc|ccccccccc|@{}}
\toprule
\multirow{3}{*}{المرحلة} & \multicolumn{3}{c|}{\begin{tabular}[c]{@{}c@{}}عدد التلامذة التاركون حسب الصف\\ والجنس للعام الدراسي `r by`\end{tabular}} & \multicolumn{3}{c|}{\begin{tabular}[c]{@{}c@{}}عدد التلامذة الناجحين للعام \\ الدراسي `r ay` حسب الصف والجنس\end{tabular}} & \multicolumn{9}{c|}{\begin{tabular}[c]{@{}c@{}}عدد التلامذة الراسبين حسب اسباب الرسوب\\ والصف والجنس للعام الدراسي `r ay`\end{tabular}}                                                                                                                               \\ \cmidrule(l){2-16} 
                         & \multicolumn{1}{C{1.3cm}|}{\multirow{2}{*}{بنين}}    & \multicolumn{1}{C{1.3cm}|}{\multirow{2}{*}{بنات}}   & \multirow{2}{*}{المجموع}   & \multicolumn{1}{C{1.3cm}|}{\multirow{2}{*}{بنين}}    & \multicolumn{1}{C{1.3cm}|}{\multirow{2}{*}{بنات}}    & \multirow{2}{*}{المجموع}   & \multicolumn{2}{c|}{الفشل في الامتحان}                      & \multicolumn{2}{c|}{تجاوز ايام الغياب}                       & \multicolumn{2}{c|}{أسباب أخرى}                               & \multicolumn{3}{c|}{المجموع}                                             \\ \cmidrule(l){8-16} 
                         & \multicolumn{1}{c|}{}                         & \multicolumn{1}{c|}{}                        &                            & \multicolumn{1}{c|}{}                         & \multicolumn{1}{c|}{}                         &                            & \multicolumn{1}{c|}{بنون}    & \multicolumn{1}{c|}{بنات}    & \multicolumn{1}{c|}{بنون}    & \multicolumn{1}{c|}{بنات}     & \multicolumn{1}{c|}{بنون}     & \multicolumn{1}{c|}{بنات}     & \multicolumn{1}{c|}{بنون}     & \multicolumn{1}{c|}{بنات}     & المجموع  \\ \midrule
الاولى                   & \multicolumn{1}{c|}{`r c11`}                  & \multicolumn{1}{c|}{`r c21`}                 & `r c31`                    & \multicolumn{1}{c|}{`r c41`}                  & \multicolumn{1}{c|}{`r c51`}                  & `r c61`                    & \multicolumn{1}{c|}{`r c71`} & \multicolumn{1}{c|}{`r c81`} & \multicolumn{1}{c|}{`r c91`} & \multicolumn{1}{c|}{`r c101`} & \multicolumn{1}{c|}{`r c111`} & \multicolumn{1}{c|}{`r c121`} & \multicolumn{1}{c|}{`r c131`} & \multicolumn{1}{c|}{`r c141`} & `r c151` \\ \midrule
الثانية                  & \multicolumn{1}{c|}{`r c12`}                  & \multicolumn{1}{c|}{`r c22`}                 & `r c32`                    & \multicolumn{1}{c|}{`r c42`}                  & \multicolumn{1}{c|}{`r c52`}                  & `r c62`                    & \multicolumn{1}{c|}{`r c72`} & \multicolumn{1}{c|}{`r c82`} & \multicolumn{1}{c|}{`r c92`} & \multicolumn{1}{c|}{`r c102`} & \multicolumn{1}{c|}{`r c112`} & \multicolumn{1}{c|}{`r c122`} & \multicolumn{1}{c|}{`r c132`} & \multicolumn{1}{c|}{`r c142`} & `r c152` \\ \midrule
الثالثة                  & \multicolumn{1}{c|}{`r c13`}                  & \multicolumn{1}{c|}{`r c23`}                 & `r c33`                    & \multicolumn{1}{c|}{`r c43`}                  & \multicolumn{1}{c|}{`r c53`}                  & `r c63`                    & \multicolumn{1}{c|}{`r c73`} & \multicolumn{1}{c|}{`r c83`} & \multicolumn{1}{c|}{`r c93`} & \multicolumn{1}{c|}{`r c103`} & \multicolumn{1}{c|}{`r c113`} & \multicolumn{1}{c|}{`r c123`} & \multicolumn{1}{c|}{`r c133`} & \multicolumn{1}{c|}{`r c143`} & `r c153` \\ \midrule
المجموع                  & \multicolumn{1}{c|}{`r c14`}                  & \multicolumn{1}{c|}{`r c24`}                 & `r c34`                    & \multicolumn{1}{c|}{`r c44`}                  & \multicolumn{1}{c|}{`r c54`}                  & `r c64`                    & \multicolumn{1}{c|}{`r c74`} & \multicolumn{1}{c|}{`r c84`} & \multicolumn{1}{c|}{`r c94`} & \multicolumn{1}{c|}{`r c104`} & \multicolumn{1}{c|}{`r c114`} & \multicolumn{1}{c|}{`r c124`} & \multicolumn{1}{c|}{`r c134`} & \multicolumn{1}{c|}{`r c144`} & `r c154` \\ \bottomrule
\end{tabular}%
\end{table}