```{r table_v1c_5, include=FALSE}


c11 <- sum(as.numeric(df$form3_b_1_2), na.rm = TRUE)
c12 <- sum(as.numeric(df$form3_b_1_7), na.rm = TRUE)
c13 <- sum(as.numeric(df$form3_b_1_12), na.rm = TRUE)
c14 <- sum(as.numeric(df$form3_b_1_17), na.rm = TRUE)
c15 <- sum(as.numeric(df$form3_b_1_22), na.rm = TRUE)
c16 <- sum(as.numeric(df$form3_b_1_27), na.rm = TRUE)
c17 <- sum(as.numeric(df$form3_b_1_32), na.rm = TRUE)
c18 <- sum(as.numeric(df$form3_b_1_37), na.rm = TRUE)

c21 <- sum(as.numeric(df$form3_b_1_3), na.rm = TRUE)
c22 <- sum(as.numeric(df$form3_b_1_8), na.rm = TRUE)
c23 <- sum(as.numeric(df$form3_b_1_13), na.rm = TRUE)
c24 <- sum(as.numeric(df$form3_b_1_18), na.rm = TRUE)
c25 <- sum(as.numeric(df$form3_b_1_23), na.rm = TRUE)
c26 <- sum(as.numeric(df$form3_b_1_28), na.rm = TRUE)
c27 <- sum(as.numeric(df$form3_b_1_33), na.rm = TRUE)
c28 <- sum(as.numeric(df$form3_b_1_38), na.rm = TRUE)

c31 <- sum(as.numeric(df$form3_b_2_2), na.rm = TRUE)
c32 <- sum(as.numeric(df$form3_b_2_7), na.rm = TRUE)
c33 <- sum(as.numeric(df$form3_b_2_12), na.rm = TRUE)
c34 <- sum(as.numeric(df$form3_b_2_17), na.rm = TRUE)
c35 <- sum(as.numeric(df$form3_b_2_22), na.rm = TRUE)
c36 <- sum(as.numeric(df$form3_b_2_27), na.rm = TRUE)
c37 <- sum(as.numeric(df$form3_b_2_32), na.rm = TRUE)
c38 <- sum(as.numeric(df$form3_b_2_37), na.rm = TRUE)

c41 <- sum(as.numeric(df$form3_b_2_3), na.rm = TRUE)
c42 <- sum(as.numeric(df$form3_b_2_8), na.rm = TRUE)
c43 <- sum(as.numeric(df$form3_b_2_13), na.rm = TRUE)
c44 <- sum(as.numeric(df$form3_b_2_18), na.rm = TRUE)
c45 <- sum(as.numeric(df$form3_b_2_23), na.rm = TRUE)
c46 <- sum(as.numeric(df$form3_b_2_28), na.rm = TRUE)
c47 <- sum(as.numeric(df$form3_b_2_33), na.rm = TRUE)
c48 <- sum(as.numeric(df$form3_b_2_38), na.rm = TRUE)

c51 <- sum(as.numeric(df$form3_b_3_2), na.rm = TRUE)
c52 <- sum(as.numeric(df$form3_b_3_7), na.rm = TRUE)
c53 <- sum(as.numeric(df$form3_b_3_12), na.rm = TRUE)
c54 <- sum(as.numeric(df$form3_b_3_17), na.rm = TRUE)
c55 <- sum(as.numeric(df$form3_b_3_22), na.rm = TRUE)
c56 <- sum(as.numeric(df$form3_b_3_27), na.rm = TRUE)
c57 <- sum(as.numeric(df$form3_b_3_32), na.rm = TRUE)
c58 <- sum(as.numeric(df$form3_b_3_37), na.rm = TRUE)

c61 <- sum(as.numeric(df$form3_b_3_3), na.rm = TRUE)
c62 <- sum(as.numeric(df$form3_b_3_8), na.rm = TRUE)
c63 <- sum(as.numeric(df$form3_b_3_13), na.rm = TRUE)
c64 <- sum(as.numeric(df$form3_b_3_18), na.rm = TRUE)
c65 <- sum(as.numeric(df$form3_b_3_23), na.rm = TRUE)
c66 <- sum(as.numeric(df$form3_b_3_28), na.rm = TRUE)
c67 <- sum(as.numeric(df$form3_b_3_33), na.rm = TRUE)
c68 <- sum(as.numeric(df$form3_b_3_38), na.rm = TRUE)

c71 <- sum(as.numeric(df$form3_b_4_2), na.rm = TRUE)
c72 <- sum(as.numeric(df$form3_b_4_7), na.rm = TRUE)
c73 <- sum(as.numeric(df$form3_b_4_12), na.rm = TRUE)
c74 <- sum(as.numeric(df$form3_b_4_17), na.rm = TRUE)
c75 <- sum(as.numeric(df$form3_b_4_22), na.rm = TRUE)
c76 <- sum(as.numeric(df$form3_b_4_27), na.rm = TRUE)
c77 <- sum(as.numeric(df$form3_b_4_32), na.rm = TRUE)
c78 <- sum(as.numeric(df$form3_b_4_37), na.rm = TRUE)

c81 <- sum(as.numeric(df$form3_b_4_3), na.rm = TRUE)
c82 <- sum(as.numeric(df$form3_b_4_8), na.rm = TRUE)
c83 <- sum(as.numeric(df$form3_b_4_13), na.rm = TRUE)
c84 <- sum(as.numeric(df$form3_b_4_18), na.rm = TRUE)
c85 <- sum(as.numeric(df$form3_b_4_23), na.rm = TRUE)
c86 <- sum(as.numeric(df$form3_b_4_28), na.rm = TRUE)
c87 <- sum(as.numeric(df$form3_b_4_33), na.rm = TRUE)
c88 <- sum(as.numeric(df$form3_b_4_38), na.rm = TRUE)

c91 <- c71 + c81 
c92 <- c72 + c82
c93 <- c73 + c83
c94 <- c74 + c84
c95 <- c75 + c85
c96 <- c76 + c86
c97 <- c77 + c87
c98 <- c78 + c88



```

\begin{table}[H]
\centering
\caption{خلاصة محافظة النجف الاشرف لمدارس التعليم المسرع}
\begin{tabular}{@{}|c|cc|cc|cc|ccc|@{}}
\toprule
\multirow{2}{*}{العمر} & \multicolumn{2}{c|}{المرحلة الاولى}    & \multicolumn{2}{c|}{المرحلة   الثانية} & \multicolumn{2}{c|}{المرحلة   الثالثة} & \multicolumn{3}{c|}{المجموع الكلي}                                    \\ \cmidrule(l){2-10} 
                       & \multicolumn{1}{c|}{بنون}    & بنات    & \multicolumn{1}{c|}{بنون}    & بنات    & \multicolumn{1}{c|}{بنون}    & بنات    & \multicolumn{1}{c|}{بنون}    & \multicolumn{1}{c|}{بنات}    & المجموع \\ \midrule
12 سنة                 & \multicolumn{1}{c|}{`r c11`} & `r c21` & \multicolumn{1}{c|}{`r c31`} & `r c41` & \multicolumn{1}{c|}{`r c51`} & `r c61` & \multicolumn{1}{c|}{`r c71`} & \multicolumn{1}{c|}{`r c81`} & `r c91` \\ \midrule
13 سنة                 & \multicolumn{1}{c|}{`r c12`} & `r c22` & \multicolumn{1}{c|}{`r c32`} & `r c42` & \multicolumn{1}{c|}{`r c52`} & `r c62` & \multicolumn{1}{c|}{`r c72`} & \multicolumn{1}{c|}{`r c82`} & `r c92` \\ \midrule
14 سنة                 & \multicolumn{1}{c|}{`r c13`} & `r c23` & \multicolumn{1}{c|}{`r c33`} & `r c43` & \multicolumn{1}{c|}{`r c53`} & `r c63` & \multicolumn{1}{c|}{`r c73`} & \multicolumn{1}{c|}{`r c83`} & `r c93` \\ \midrule
15 سنة                 & \multicolumn{1}{c|}{`r c14`} & `r c24` & \multicolumn{1}{c|}{`r c34`} & `r c44` & \multicolumn{1}{c|}{`r c54`} & `r c64` & \multicolumn{1}{c|}{`r c74`} & \multicolumn{1}{c|}{`r c84`} & `r c94` \\ \midrule
16 سنة                 & \multicolumn{1}{c|}{`r c15`} & `r c25` & \multicolumn{1}{c|}{`r c35`} & `r c45` & \multicolumn{1}{c|}{`r c55`} & `r c65` & \multicolumn{1}{c|}{`r c75`} & \multicolumn{1}{c|}{`r c85`} & `r c95` \\ \midrule
17 سنة                 & \multicolumn{1}{c|}{`r c16`} & `r c26` & \multicolumn{1}{c|}{`r c36`} & `r c46` & \multicolumn{1}{c|}{`r c56`} & `r c66` & \multicolumn{1}{c|}{`r c76`} & \multicolumn{1}{c|}{`r c86`} & `r c96` \\ \midrule
18 سنة                 & \multicolumn{1}{c|}{`r c17`} & `r c27` & \multicolumn{1}{c|}{`r c37`} & `r c47` & \multicolumn{1}{c|}{`r c57`} & `r c67` & \multicolumn{1}{c|}{`r c77`} & \multicolumn{1}{c|}{`r c87`} & `r c97` \\ \midrule
المجموع                & \multicolumn{1}{c|}{`r c18`} & `r c28` & \multicolumn{1}{c|}{`r c38`} & `r c48` & \multicolumn{1}{c|}{`r c58`} & `r c68` & \multicolumn{1}{c|}{`r c78`} & \multicolumn{1}{c|}{`r c88`} & `r c98` \\ \bottomrule
\end{tabular}%
\end{table}
