
```{r table_v1_5, include=FALSE}
## المجموعة الأولى (q54)
c11 <- nrow(df[which(df$q54 == "1"), ])
c21 <- nrow(df[which(df$q54 == "2"), ])
c31 <- nrow(df[which(df$q54 == "3"), ])

# المجموعة الثانية (q53)
c41 <- nrow(df[which(df$q53 == "1"), ])
c51 <- nrow(df[which(df$q53 == "2"), ])
c61 <- nrow(df[which(df$q53 == "3"), ])

# المجموعة الثالثة (q55)
c71 <- nrow(df[which(df$q55 == "1"), ])
c81 <- nrow(df[which(df$q55 == "2"), ])
c91 <- nrow(df[which(df$q55 == "3"), ])

# المجموعة الرابعة (q38)
c101 <- nrow(df[which(df$q38 == "1"), ])
c111 <- nrow(df[which(df$q38 == "2"), ])

# المجموعة الخامسة (q47)
c121 <- nrow(df[which(df$q47 == "1"), ])
c131 <- nrow(df[which(df$q47 == "4"), ])
c141 <- nrow(df[which(df$q47 == "2"), ])
c151 <- nrow(df[which(df$q47 == "5"), ])
c161 <- nrow(df[which(df$q47 == "6"), ])
c171 <- nrow(df[which(df$q47 == "7"), ])
c181 <- c121 + c131 + c141 + c151 + c171

# المجموعة الأخيرة (q48, q49, q50, q51)
c191 <- nrow(df[which(df$q48 == "1"), ])
c201 <- nrow(df[which(df$q49 == "1"), ])
c211 <- nrow(df[which(df$q50 == "1"), ])
c221 <- nrow(df[which(df$q51 == "1"), ])
```


\begin{table}[H]
\centering
\caption{عدد الابنية المدرسية وعدد المكتبات}
\resizebox{\columnwidth}{!}{%
\begin{tabular}{@{}|cccccccccccccccccc|@{}}
\toprule
\multicolumn{3}{|c|}{عدد الابنية حسب العائدية}                                                                                                                                                            & \multicolumn{3}{c|}{عدد الابنية التي تشغلها}                                                                                                                                                                                                     & \multicolumn{3}{c|}{عدد الابنية حسب الحالة العمرانية}                                                                                                                                                                                     & \multicolumn{2}{c|}{عدد الابنية حسب نوع البناء}                                                                                         & \multicolumn{6}{c|}{عدد الابنية حسب مادة البناء}                                                                                                                                                                                                                                                                                                                                                                                        & \multirow{3}{*}{\begin{tabular}[c]{@{}c@{}}المجموع\\ الكلي\\ للابنية\end{tabular}} \\ \cmidrule(r){1-17}
\multicolumn{2}{|c|}{حكومية}                                                                                                                              & \multicolumn{1}{c|}{\multirow{2}{*}{مستاجرة}} & \multicolumn{1}{c|}{\multirow{2}{*}{\begin{tabular}[c]{@{}c@{}}مدرسة\\ واحدة\end{tabular}}} & \multicolumn{1}{c|}{\multirow{2}{*}{مدرستان}} & \multicolumn{1}{c|}{\multirow{2}{*}{\begin{tabular}[c]{@{}c@{}}ثلاث\\ مدارس\\ فاكثر\end{tabular}}} & \multicolumn{1}{c|}{\multirow{2}{*}{صالحة}} & \multicolumn{1}{c|}{\multirow{2}{*}{\begin{tabular}[c]{@{}c@{}}بحاجة الى\\ ترميم\end{tabular}}} & \multicolumn{1}{c|}{\multirow{2}{*}{\begin{tabular}[c]{@{}c@{}}غير\\ صالحة\end{tabular}}} & \multicolumn{1}{c|}{\multirow{2}{*}{مدرسي}} & \multicolumn{1}{c|}{\multirow{2}{*}{\begin{tabular}[c]{@{}c@{}}غير\\ مدرسي\end{tabular}}} & \multicolumn{1}{c|}{\multirow{2}{*}{\begin{tabular}[c]{@{}c@{}}طابوق\\ او حجر\end{tabular}}} & \multicolumn{1}{c|}{\multirow{2}{*}{بناء جاهز}} & \multicolumn{1}{c|}{\multirow{2}{*}{\begin{tabular}[c]{@{}c@{}}طين\\ او صريفة\end{tabular}}} & \multicolumn{1}{c|}{\multirow{2}{*}{\begin{tabular}[c]{@{}c@{}}هياكل\\ حديدية\end{tabular}}} & \multicolumn{1}{c|}{\multirow{2}{*}{كرفان}} & \multicolumn{1}{c|}{\multirow{2}{*}{اخرى}} &                                                                                    \\ \cmidrule(r){1-2}
\multicolumn{1}{|c|}{\begin{tabular}[c]{@{}c@{}}عائدة\\ للتربية\end{tabular}} & \multicolumn{1}{c|}{\begin{tabular}[c]{@{}c@{}}لجهات\\ اخرى\end{tabular}} & \multicolumn{1}{c|}{}                         & \multicolumn{1}{c|}{}                                                                       & \multicolumn{1}{c|}{}                         & \multicolumn{1}{c|}{}                                                                              & \multicolumn{1}{c|}{}                       & \multicolumn{1}{c|}{}                                                                           & \multicolumn{1}{c|}{}                                                                     & \multicolumn{1}{c|}{}                       & \multicolumn{1}{c|}{}                                                                     & \multicolumn{1}{c|}{}                                                                        & \multicolumn{1}{c|}{}                           & \multicolumn{1}{c|}{}                                                                        & \multicolumn{1}{c|}{}                                                                        & \multicolumn{1}{c|}{}                       & \multicolumn{1}{c|}{}                      &                                                                                    \\ \midrule
\multicolumn{1}{|c|}{`r c11`}                                                 & \multicolumn{1}{c|}{`r c21`}                                              & \multicolumn{1}{c|}{`r c31`}                  & \multicolumn{1}{c|}{`r c41`}                                                                & \multicolumn{1}{c|}{`r c51`}                  & \multicolumn{1}{c|}{`r c61`}                                                                       & \multicolumn{1}{c|}{`r c71`}                & \multicolumn{1}{c|}{`r c81`}                                                                    & \multicolumn{1}{c|}{`r c91`}                                                              & \multicolumn{1}{c|}{`r c101`}               & \multicolumn{1}{c|}{`r c111`}                                                             & \multicolumn{1}{c|}{`r c121`}                                                                & \multicolumn{1}{c|}{`r c131`}                   & \multicolumn{1}{c|}{`r c141`}                                                                & \multicolumn{1}{c|}{`r c151`}                                                                & \multicolumn{1}{c|}{`r c161`}               & \multicolumn{1}{c|}{`r c171`}              & `r c181`                                                                           \\ \midrule
\multicolumn{18}{|c|}{عدد الابنية حسب نوع الخدمات}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                \\ \midrule
\multicolumn{5}{|c|}{عدد الابنية التي تتوفر فيها مرافق صحية}                                                                                                                                                                                                                                                                                            & \multicolumn{4}{l|}{عدد الابنية التي يصلها ماء صالح للشرب}                                                                                                                                                                                                                                                                                     & \multicolumn{4}{c|}{عدد الابنية المزودة بخدمة مجاري}                                                                                                                                                                                                                                     & \multicolumn{5}{c|}{عدد الابنية التي تحتوي سياج مدرسي}                                                                                                                                                                                                                                                                                                                      \\ \midrule
\multicolumn{5}{|c|}{`r c191`}                                                                                                                                                                                                                                                                                                                          & \multicolumn{4}{c|}{`r c201`}                                                                                                                                                                                                                                                                                                                  & \multicolumn{4}{c|}{`r c211`}                                                                                                                                                                                                                                                            & \multicolumn{5}{c|}{`r c221`}                                                                                                                                                                                                                                                                                                                                               \\ \bottomrule
\end{tabular}%
}
\end{table}
