```{r table_v1_3, include=FALSE}

#class 1
c11 <- sum(df$table26a_2, na.rm = TRUE)
c12 <- sum(df$table26a_7, na.rm = TRUE)
c13 <- sum(df$table26a_12, na.rm = TRUE)
c14 <- sum(df$table26a_17, na.rm = TRUE)
c15 <- sum(df$table26a_22, na.rm = TRUE)
c16 <- sum(df$table26a_27, na.rm = TRUE)
c17 <- sum(df$table26a_32, na.rm = TRUE)
###########################################
c21 <- sum(df$table26a_3, na.rm = TRUE)
c22 <- sum(df$table26a_8, na.rm = TRUE)
c23 <- sum(df$table26a_13, na.rm = TRUE)
c24 <- sum(df$table26a_18, na.rm = TRUE)
c25 <- sum(df$table26a_23, na.rm = TRUE)
c26 <- sum(df$table26a_28, na.rm = TRUE)
c27 <- sum(df$table26a_33, na.rm = TRUE)
###########################################
#calss 2
c31 <- sum(df$table26b_2, na.rm = TRUE)
c32 <- sum(df$table26b_7, na.rm = TRUE)
c33 <- sum(df$table26b_12, na.rm = TRUE)
c34 <- sum(df$table26b_17, na.rm = TRUE)
c35 <- sum(df$table26b_22, na.rm = TRUE)
c36 <- sum(df$table26b_27, na.rm = TRUE)
c37 <- sum(df$table26b_32, na.rm = TRUE)
###########################################
c41 <- sum(df$table26b_3, na.rm = TRUE)
c42 <- sum(df$table26b_8, na.rm = TRUE)
c43 <- sum(df$table26b_13, na.rm = TRUE)
c44 <- sum(df$table26b_18, na.rm = TRUE)
c45 <- sum(df$table26b_23, na.rm = TRUE)
c46 <- sum(df$table26b_28, na.rm = TRUE)
c47 <- sum(df$table26b_33, na.rm = TRUE)
###########################################
#class 3
c51 <- sum(df$table26c_2, na.rm = TRUE)
c52 <- sum(df$table26c_7, na.rm = TRUE)
c53 <- sum(df$table26c_12, na.rm = TRUE)
c54 <- sum(df$table26c_17, na.rm = TRUE)
c55 <- sum(df$table26c_22, na.rm = TRUE)
c56 <- sum(df$table26c_27, na.rm = TRUE)
c57 <- sum(df$table26c_32, na.rm = TRUE)
###########################################
c61 <- sum(df$table26c_3, na.rm = TRUE)
c62 <- sum(df$table26c_8, na.rm = TRUE)
c63 <- sum(df$table26c_13, na.rm = TRUE)
c64 <- sum(df$table26c_18, na.rm = TRUE)
c65 <- sum(df$table26c_23, na.rm = TRUE)
c66 <- sum(df$table26c_28, na.rm = TRUE)
c67 <- sum(df$table26c_33, na.rm = TRUE)
###########################################
#class 4
c71 <- sum(df$table26d_2, na.rm = TRUE)
c72 <- sum(df$table26d_7, na.rm = TRUE)
c73 <- sum(df$table26d_12, na.rm = TRUE)
c74 <- sum(df$table26d_17, na.rm = TRUE)
c75 <- sum(df$table26d_22, na.rm = TRUE)
c76 <- sum(df$table26d_27, na.rm = TRUE)
c77 <- sum(df$table26d_32, na.rm = TRUE)
###########################################
c81 <- sum(df$table26d_3, na.rm = TRUE)
c82 <- sum(df$table26d_8, na.rm = TRUE)
c83 <- sum(df$table26d_13, na.rm = TRUE)
c84 <- sum(df$table26d_18, na.rm = TRUE)
c85 <- sum(df$table26d_23, na.rm = TRUE)
c86 <- sum(df$table26d_28, na.rm = TRUE)
c87 <- sum(df$table26d_33, na.rm = TRUE)
###########################################
#class 5
c91 <- sum(df$table26e_2, na.rm = TRUE)
c92 <- sum(df$table26e_7, na.rm = TRUE)
c93 <- sum(df$table26e_12, na.rm = TRUE)
c94 <- sum(df$table26e_17, na.rm = TRUE)
c95 <- sum(df$table26e_22, na.rm = TRUE)
c96 <- sum(df$table26e_27, na.rm = TRUE)
c97 <- sum(df$table26e_32, na.rm = TRUE)
###########################################
c101 <- sum(df$table26e_3, na.rm = TRUE)
c102 <- sum(df$table26e_8, na.rm = TRUE)
c103 <- sum(df$table26e_13, na.rm = TRUE)
c104 <- sum(df$table26e_18, na.rm = TRUE)
c105 <- sum(df$table26e_23, na.rm = TRUE)
c106 <- sum(df$table26e_28, na.rm = TRUE)
c107 <- sum(df$table26e_33, na.rm = TRUE)
###########################################
#class 6
c111 <- sum(df$table26f_2, na.rm = TRUE)
c112 <- sum(df$table26f_7, na.rm = TRUE)
c113 <- sum(df$table26f_12, na.rm = TRUE)
c114 <- sum(df$table26f_17, na.rm = TRUE)
c115 <- sum(df$table26f_22, na.rm = TRUE)
c116 <- sum(df$table26f_27, na.rm = TRUE)
c117 <- sum(df$table26f_32, na.rm = TRUE)
###########################################
c121 <- sum(df$table26f_3, na.rm = TRUE)
c122 <- sum(df$table26f_8, na.rm = TRUE)
c123 <- sum(df$table26f_13, na.rm = TRUE)
c124 <- sum(df$table26f_18, na.rm = TRUE)
c125 <- sum(df$table26f_23, na.rm = TRUE)
c126 <- sum(df$table26f_28, na.rm = TRUE)
c127 <- sum(df$table26f_33, na.rm = TRUE)
###########################################
#total boyes
c131 <- c11
c132 <- c12
c133 <- c13 + c31
c134 <- c14 + c32 + c51
c135 <- c15 + c33 + c52 + c71
c136 <- c16 + c34 + c53 + c72 + c91
c137 <- c35 + c54 + c73 + c92 + c111
c138 <- c55 + c74 + c93 + c112
c139 <- c75 + c94 + c113
c1310 <- c95 + c114
c1311 <- c115
c1312 <- c17 + c36 + c56 + c76 + c96 + c116
###########################################
#total girls
c141 <- c21
c142 <- c22
c143 <- c23 + c41
c144 <- c24 + c42 + c61
c145 <- c25 + c43 + c62 + c81
c146 <- c26 + c44 + c63 + c82 + c101
c147 <- c45 + c64 + c83 + c102 + c121
c148 <- c65 + c84 + c103 + c122
c149 <- c85 + c104 + c123
c1410 <- c105 + c124
c1411 <- c125
c1412 <- c27 + c46 + c66 + c86 + c106 + c126
###########################################
#total sum
c151 <- c131 + c141
c152 <- c132 + c142
c153 <- c133 + c143
c154 <- c134 + c144
c155 <- c135 + c145
c156 <- c136 + c146
c157 <- c137 + c147
c158 <- c138 + c148
c159 <- c139 + c149
c1510 <- c1310 + c1410
c1511 <- c1311 + c1411
c1512 <- c1312 + c1412

```

\begin{table}[H]
\centering
\caption{عدد التلامذة المسجلين حسب الصف والعمروالجنس}
\begin{tabular}{@{}|c|cccccccccccc|ccc|@{}}
\toprule
الصف         & \multicolumn{2}{c|}{الأول}                                    & \multicolumn{2}{c|}{الثاني}                                   & \multicolumn{2}{c|}{الثالث}                                   & \multicolumn{2}{c|}{الرابع}                                   & \multicolumn{2}{c|}{الخامس}                                   & \multicolumn{2}{c|}{السادس}               & \multicolumn{3}{c|}{المجموع}                                                \\ \midrule
الجنس        & \multicolumn{1}{c|}{بنون}    & \multicolumn{1}{c|}{بنات}      & \multicolumn{1}{c|}{بنون}    & \multicolumn{1}{c|}{بنات}      & \multicolumn{1}{c|}{بنون}    & \multicolumn{1}{c|}{بنات}      & \multicolumn{1}{c|}{بنون}    & \multicolumn{1}{c|}{بنات}      & \multicolumn{1}{c|}{بنون}    & \multicolumn{1}{c|}{بنات}      & \multicolumn{1}{c|}{بنون}     & بنات      & \multicolumn{1}{c|}{بنون}      & \multicolumn{1}{c|}{بنات}      & المجموع   \\ \midrule
عمر 5        & \multicolumn{1}{c|}{`r c11`} & \multicolumn{1}{c|}{`r c21`}   &                              & \textbf{}                      &                              & \textbf{}                      &                              & \textbf{}                      &                              & \textbf{}                      &                               & \textbf{} & \multicolumn{1}{c|}{`r c131`}  & \multicolumn{1}{c|}{`r c141`}  & `r c151`  \\ \cmidrule(r){1-3} \cmidrule(l){14-16} 
عمر6         & \multicolumn{1}{c|}{`r c12`} & \multicolumn{1}{c|}{`r c22`}   & \textbf{}                    & \textbf{}                      & \textbf{}                    & \textbf{}                      & \textbf{}                    & \textbf{}                      & \textbf{}                    & \textbf{}                      & \textbf{}                     & \textbf{} & \multicolumn{1}{c|}{`r c132`}  & \multicolumn{1}{c|}{`r c142`}  & `r c152`  \\ \cmidrule(r){1-5} \cmidrule(l){14-16} 
عمر 7        & \multicolumn{1}{c|}{`r c13`} & \multicolumn{1}{c|}{`r c23`}   & \multicolumn{1}{c|}{`r c31`} & \multicolumn{1}{c|}{`r c41`}   & \textbf{}                    & \textbf{}                      & \textbf{}                    & \textbf{}                      & \textbf{}                    & \textbf{}                      & \textbf{}                     & \textbf{} & \multicolumn{1}{c|}{`r c133`}  & \multicolumn{1}{c|}{`r c143`}  & `r c153`  \\ \cmidrule(r){1-7} \cmidrule(l){14-16} 
عمر 8        & \multicolumn{1}{c|}{`r c14`} & \multicolumn{1}{c|}{`r c24`}   & \multicolumn{1}{c|}{`r c32`} & \multicolumn{1}{c|}{`r c42`}   & \multicolumn{1}{c|}{`r c51`} & \multicolumn{1}{c|}{`r c61`}   & \textbf{}                    & \textbf{}                      & \textbf{}                    & \textbf{}                      & \textbf{}                     & \textbf{} & \multicolumn{1}{c|}{`r c134`}  & \multicolumn{1}{c|}{`r c144`}  & `r c154`  \\ \cmidrule(r){1-9} \cmidrule(l){14-16} 
عمر 9        & \multicolumn{1}{c|}{`r c15`} & \multicolumn{1}{c|}{`r c25`}   & \multicolumn{1}{c|}{`r c33`} & \multicolumn{1}{c|}{`r c43`}   & \multicolumn{1}{c|}{`r c52`} & \multicolumn{1}{c|}{`r c62`}   & \multicolumn{1}{c|}{`r c71`} & \multicolumn{1}{c|}{`r c81`}   & \textbf{}                    & \textbf{}                      & \textbf{}                     & \textbf{} & \multicolumn{1}{c|}{`r c135`}  & \multicolumn{1}{c|}{`r c145`}  & `r c155`  \\ \cmidrule(r){1-11} \cmidrule(l){14-16} 
عمر 10       & \multicolumn{1}{c|}{`r c16`} & \multicolumn{1}{c|}{`r c26`}   & \multicolumn{1}{c|}{`r c34`} & \multicolumn{1}{c|}{`r c44`}   & \multicolumn{1}{c|}{`r c53`} & \multicolumn{1}{c|}{`r c63`}   & \multicolumn{1}{c|}{`r c72`} & \multicolumn{1}{c|}{`r c82`}   & \multicolumn{1}{c|}{`r c91`} & \multicolumn{1}{c|}{`r c101`}  & \textbf{}                     & \textbf{} & \multicolumn{1}{c|}{`r c136`}  & \multicolumn{1}{c|}{`r c146`}  & `r c156`  \\ \midrule
عمر 11       &                              & \multicolumn{1}{c|}{\textbf{}} & \multicolumn{1}{c|}{`r c35`} & \multicolumn{1}{c|}{`r c45`}   & \multicolumn{1}{c|}{`r c54`} & \multicolumn{1}{c|}{`r c64`}   & \multicolumn{1}{c|}{`r c73`} & \multicolumn{1}{c|}{`r c83`}   & \multicolumn{1}{c|}{`r c92`} & \multicolumn{1}{c|}{`r c102`}  & \multicolumn{1}{c|}{`r c111`} & `r c121`  & \multicolumn{1}{c|}{`r c137`}  & \multicolumn{1}{c|}{`r c147`}  & `r c157`  \\ \cmidrule(r){1-1} \cmidrule(l){4-16} 
عمر 12       & \textbf{}                    & \textbf{}                      &                              & \multicolumn{1}{c|}{\textbf{}} & \multicolumn{1}{c|}{`r c55`} & \multicolumn{1}{c|}{`r c65`}   & \multicolumn{1}{c|}{`r c74`} & \multicolumn{1}{c|}{`r c84`}   & \multicolumn{1}{c|}{`r c93`} & \multicolumn{1}{c|}{`r c103`}  & \multicolumn{1}{c|}{`r c112`} & `r c122`  & \multicolumn{1}{c|}{`r c138`}  & \multicolumn{1}{c|}{`r c148`}  & `r c158`  \\ \cmidrule(r){1-1} \cmidrule(l){6-16} 
عمر 13       & \textbf{}                    & \textbf{}                      & \textbf{}                    & \textbf{}                      &                              & \multicolumn{1}{c|}{\textbf{}} & \multicolumn{1}{c|}{`r c75`} & \multicolumn{1}{c|}{`r c85`}   & \multicolumn{1}{c|}{`r c94`} & \multicolumn{1}{c|}{`r c104`}  & \multicolumn{1}{c|}{`r c113`} & `r c123`  & \multicolumn{1}{c|}{`r c139`}  & \multicolumn{1}{c|}{`r c149`}  & `r c159`  \\ \cmidrule(r){1-1} \cmidrule(l){8-16} 
عمر14        & \textbf{}                    & \textbf{}                      & \textbf{}                    & \textbf{}                      & \textbf{}                    & \textbf{}                      &                              & \multicolumn{1}{c|}{\textbf{}} & \multicolumn{1}{c|}{`r c95`} & \multicolumn{1}{c|}{`r c105`}  & \multicolumn{1}{c|}{`r c114`} & `r c124`  & \multicolumn{1}{c|}{`r c1310`} & \multicolumn{1}{c|}{`r c1410`} & `r c1510` \\ \cmidrule(r){1-1} \cmidrule(l){10-16} 
عمر 15 فأكثر & \textbf{}                    & \textbf{}                      & \textbf{}                    & \textbf{}                      & \textbf{}                    & \textbf{}                      & \textbf{}                    & \textbf{}                      &                              & \multicolumn{1}{c|}{\textbf{}} & \multicolumn{1}{c|}{`r c115`} & `r c125`  & \multicolumn{1}{c|}{`r c1311`} & \multicolumn{1}{c|}{`r c1411`} & `r c1511` \\ \midrule
المجموع      & \multicolumn{1}{c|}{`r c17`} & \multicolumn{1}{c|}{`r c27`}   & \multicolumn{1}{c|}{`r c36`} & \multicolumn{1}{c|}{`r c46`}   & \multicolumn{1}{c|}{`r c56`} & \multicolumn{1}{c|}{`r c66`}   & \multicolumn{1}{c|}{`r c76`} & \multicolumn{1}{c|}{`r c86`}   & \multicolumn{1}{c|}{`r c96`} & \multicolumn{1}{c|}{`r c106`}  & \multicolumn{1}{c|}{`r c116`} & `r c126`  & \multicolumn{1}{c|}{`r c1312`} & \multicolumn{1}{c|}{`r c1412`} & `r c1512` \\ \bottomrule
\end{tabular}
\end{table}
