```{r table_v1_7, include=FALSE}

c11 <- nrow(df[which(df$q62 == "1"), ])
c21 <- nrow(df[which(df$q62 == "2"), ])
c31 <- sum(as.numeric(df$q65c), na.rm = TRUE)


c41 <- nrow(df[which(df$q66 == "1"), ])
c51 <- nrow(df[which(df$q66 == "2"), ])

c61 <- nrow(df[which(df$qtype/1 == "1"), ])
c71 <- nrow(df[which(df$qtype/2 == "1"), ])
c81 <- nrow(df[which(df$qtype/3 == "1"), ])
c91 <- nrow(df[which(df$qtype/4 == "1"), ])
c101 <- nrow(df[which(df$qtype/5 == "1"), ])
c111 <- nrow(df[which(df$qtype/6 == "1"), ])
c121 <- nrow(df[which(df$qtype/7 == "1"), ])

```

\begin{table}[H]
\centering
\caption{عدد المكتبات والمختبرات}
\begin{tabular}{@{}|ccc|ccccccccc|@{}}
\toprule
\multicolumn{3}{|c|}{\multirow{2}{*}{\textbf{المكتبات المدرسية}}}                                         & \multicolumn{9}{c|}{\textbf{المختبرات المدرسية}}                                                                                                                                                                                                                                                                                                                                                                                                                \\ \cmidrule(l){4-12} 
\multicolumn{3}{|c|}{}                                                                                    & \multicolumn{2}{c|}{\textbf{هل توجد   مختبرات}}                                                         & \multicolumn{5}{c|}{\textbf{المختبرات العلمية}}                                                                                                                                                                                                & \multicolumn{1}{c|}{\multirow{3}{*}{\textbf{مختبر اللغة}}} & \multirow{3}{*}{\textbf{مختبر الحاسوب}} \\ \cmidrule(r){1-10}
\multicolumn{2}{|c|}{\textbf{عدد المكتبات}}                       & \multirow{2}{*}{\textbf{عدد   الكتب}} & \multicolumn{1}{c|}{\multirow{2}{*}{\textbf{نعم}}} & \multicolumn{1}{c|}{\multirow{2}{*}{\textbf{كلا}}} & \multicolumn{1}{c|}{\textbf{العلوم}}          & \multicolumn{1}{c|}{\textbf{الفيزياء}}        & \multicolumn{1}{c|}{\textbf{الكيمياء}}        & \multicolumn{1}{c|}{\textbf{الاحياء}}         & \multicolumn{1}{c|}{\textbf{مجمع المختبرات}}   & \multicolumn{1}{c|}{}                                      &                                         \\ \cmidrule(r){1-2} \cmidrule(lr){6-10}
\multicolumn{1}{|c|}{نعم}     & \multicolumn{1}{c|}{\textbf{كلا}} &                                       & \multicolumn{1}{c|}{}                              & \multicolumn{1}{c|}{}                              & \multicolumn{1}{c|}{\multirow{2}{*}{`r c61`}} & \multicolumn{1}{c|}{\multirow{2}{*}{`r c71`}} & \multicolumn{1}{c|}{\multirow{2}{*}{`r c81`}} & \multicolumn{1}{c|}{\multirow{2}{*}{`r c91`}} & \multicolumn{1}{c|}{\multirow{2}{*}{`r c101`}} & \multicolumn{1}{c|}{}                                      &                                         \\ \cmidrule(r){1-5} \cmidrule(l){11-12} 
\multicolumn{1}{|c|}{`r c11`} & \multicolumn{1}{c|}{`r c21`}      & `r c31`                               & \multicolumn{1}{c|}{`r c41`}                       & \multicolumn{1}{c|}{`r c51`}                       & \multicolumn{1}{c|}{}                         & \multicolumn{1}{c|}{}                         & \multicolumn{1}{c|}{}                         & \multicolumn{1}{c|}{}                         & \multicolumn{1}{c|}{}                          & \multicolumn{1}{c|}{`r c111`}                              & `r c121`                                \\ \bottomrule
\end{tabular}%}
\end{table}