```{r table_v1_9, include=FALSE}

c11 <- sum(as.numeric(df$table29_2), na.rm = TRUE)
c21 <- sum(as.numeric(df$table29_3), na.rm = TRUE)
c31 <- sum(as.numeric(df$table29_sumrow1), na.rm = TRUE)

c12 <- sum(as.numeric(df$table29_7), na.rm = TRUE)
c22 <- sum(as.numeric(df$table29_8), na.rm = TRUE)
c32 <- sum(as.numeric(df$table29_sumrow2), na.rm = TRUE)

c13 <- sum(as.numeric(df$table29_12), na.rm = TRUE)
c23 <- sum(as.numeric(df$table29_13), na.rm = TRUE)
c33 <- sum(as.numeric(df$table29_sumrow3), na.rm = TRUE)

c14 <- sum(as.numeric(df$table29_17), na.rm = TRUE)
c24 <- sum(as.numeric(df$table29_18), na.rm = TRUE)
c34 <- sum(as.numeric(df$table29_sumrow4), na.rm = TRUE)

c15 <- sum(as.numeric(df$table29_22), na.rm = TRUE)
c25 <- sum(as.numeric(df$table29_23), na.rm = TRUE)
c35 <- sum(as.numeric(df$table29_sumrow5), na.rm = TRUE)

c16 <- sum(as.numeric(df$table29_27), na.rm = TRUE)
c26 <- sum(as.numeric(df$table29_28), na.rm = TRUE)
c36 <- sum(as.numeric(df$table29_sumrow6), na.rm = TRUE)

c17 <- sum(as.numeric(df$table29_32), na.rm = TRUE)
c27 <- sum(as.numeric(df$table29_33), na.rm = TRUE)
c37 <- sum(as.numeric(df$table29_sumrow7), na.rm = TRUE)

##############################################################
c41 <- sum(as.numeric(df$table30_2), na.rm = TRUE)
c51 <- sum(as.numeric(df$table30_3), na.rm = TRUE)
c61 <- sum(as.numeric(df$table30_sumrow1), na.rm = TRUE)

c42 <- sum(as.numeric(df$table30_7), na.rm = TRUE)
c52 <- sum(as.numeric(df$table30_8), na.rm = TRUE)
c62 <- sum(as.numeric(df$table30_sumrow2), na.rm = TRUE)

c43 <- sum(as.numeric(df$table30_12), na.rm = TRUE)
c53 <- sum(as.numeric(df$table30_13), na.rm = TRUE)
c63 <- sum(as.numeric(df$table30_sumrow3), na.rm = TRUE)

c44 <- sum(as.numeric(df$table30_17), na.rm = TRUE)
c54 <- sum(as.numeric(df$table30_18), na.rm = TRUE)
c64 <- sum(as.numeric(df$table30_sumrow4), na.rm = TRUE)

c45 <- sum(as.numeric(df$table30_22), na.rm = TRUE)
c55 <- sum(as.numeric(df$table30_23), na.rm = TRUE)
c65 <- sum(as.numeric(df$table30_sumrow5), na.rm = TRUE)

c46 <- sum(as.numeric(df$table30_27), na.rm = TRUE)
c56 <- sum(as.numeric(df$table30_28), na.rm = TRUE)
c66 <- sum(as.numeric(df$table30_sumrow6), na.rm = TRUE)

c47 <- sum(as.numeric(df$table30_32), na.rm = TRUE)
c57 <- sum(as.numeric(df$table30_33), na.rm = TRUE)
c67 <- sum(as.numeric(df$table30_sumrow7), na.rm = TRUE)

##############################################################
c71 <- sum(as.numeric(df$table31a_2), na.rm = TRUE)
c81 <- sum(as.numeric(df$table31a_3), na.rm = TRUE)

c72 <- sum(as.numeric(df$table31a_7), na.rm = TRUE)
c82 <- sum(as.numeric(df$table31a_8), na.rm = TRUE)

c73 <- sum(as.numeric(df$table31a_12), na.rm = TRUE)
c83 <- sum(as.numeric(df$table31a_13), na.rm = TRUE)

c74 <- sum(as.numeric(df$table31a_17), na.rm = TRUE)
c84 <- sum(as.numeric(df$table31a_18), na.rm = TRUE)

c75 <- sum(as.numeric(df$table31a_22), na.rm = TRUE)
c85 <- sum(as.numeric(df$table31a_23), na.rm = TRUE)

c76 <- sum(as.numeric(df$table31a_27), na.rm = TRUE)
c86 <- sum(as.numeric(df$table31a_28), na.rm = TRUE)

c77 <- sum(as.numeric(df$table31a_32), na.rm = TRUE)
c87 <- sum(as.numeric(df$table31a_33), na.rm = TRUE)

##############################################################
c91 <- sum(as.numeric(df$table31b_2), na.rm = TRUE)
c101 <- sum(as.numeric(df$table31b_3), na.rm = TRUE)

c92 <- sum(as.numeric(df$table31b_7), na.rm = TRUE)
c102 <- sum(as.numeric(df$table31b_8), na.rm = TRUE)

c93 <- sum(as.numeric(df$table31b_12), na.rm = TRUE)
c103 <- sum(as.numeric(df$table31b_13), na.rm = TRUE)

c94 <- sum(as.numeric(df$table31b_17), na.rm = TRUE)
c104 <- sum(as.numeric(df$table31b_18), na.rm = TRUE)

c95 <- sum(as.numeric(df$table31b_22), na.rm = TRUE)
c105 <- sum(as.numeric(df$table31b_23), na.rm = TRUE)

c96 <- sum(as.numeric(df$table31b_27), na.rm = TRUE)
c106 <- sum(as.numeric(df$table31b_28), na.rm = TRUE)

c97 <- sum(as.numeric(df$table31b_32), na.rm = TRUE)
c107 <- sum(as.numeric(df$table31b_33), na.rm = TRUE)
##############################################################
c111 <- sum(as.numeric(df$table31c_2), na.rm = TRUE)
c121 <- sum(as.numeric(df$table31c_3), na.rm = TRUE)

c112 <- sum(as.numeric(df$table31c_7), na.rm = TRUE)
c122 <- sum(as.numeric(df$table31c_8), na.rm = TRUE)

c113 <- sum(as.numeric(df$table31c_12), na.rm = TRUE)
c123 <- sum(as.numeric(df$table31c_13), na.rm = TRUE)

c114 <- sum(as.numeric(df$table31c_17), na.rm = TRUE)
c124 <- sum(as.numeric(df$table31c_18), na.rm = TRUE)

c115 <- sum(as.numeric(df$table31c_22), na.rm = TRUE)
c125 <- sum(as.numeric(df$table31c_23), na.rm = TRUE)

c116 <- sum(as.numeric(df$table31c_27), na.rm = TRUE)
c126 <- sum(as.numeric(df$table31c_28), na.rm = TRUE)

c117 <- sum(as.numeric(df$table31c_32), na.rm = TRUE)
c127 <- sum(as.numeric(df$table31c_33), na.rm = TRUE)

##############################################################
c131 <- sum(as.numeric(df$table31d_2), na.rm = TRUE)
c141 <- sum(as.numeric(df$table31d_3), na.rm = TRUE)
c151 <- sum(as.numeric(df$table31d_sumrow1), na.rm = TRUE)

c132 <- sum(as.numeric(df$table31d_7), na.rm = TRUE)
c142 <- sum(as.numeric(df$table31d_8), na.rm = TRUE)
c152 <- sum(as.numeric(df$table31d_sumrow2), na.rm = TRUE)

c133 <- sum(as.numeric(df$table31d_12), na.rm = TRUE)
c143 <- sum(as.numeric(df$table31d_13), na.rm = TRUE)
c153 <- sum(as.numeric(df$table31d_sumrow3), na.rm = TRUE)

c134 <- sum(as.numeric(df$table31d_17), na.rm = TRUE)
c144 <- sum(as.numeric(df$table31d_18), na.rm = TRUE)
c154 <- sum(as.numeric(df$table31d_sumrow4), na.rm = TRUE)

c135 <- sum(as.numeric(df$table31d_22), na.rm = TRUE)
c145 <- sum(as.numeric(df$table31d_23), na.rm = TRUE)
c155 <- sum(as.numeric(df$table31d_sumrow5), na.rm = TRUE)

c136 <- sum(as.numeric(df$table31d_27), na.rm = TRUE)
c146 <- sum(as.numeric(df$table31d_28), na.rm = TRUE)
c156 <- sum(as.numeric(df$table31d_sumrow6), na.rm = TRUE)

c137 <- sum(as.numeric(df$table31d_32), na.rm = TRUE)
c147 <- sum(as.numeric(df$table31d_33), na.rm = TRUE)
c157 <- sum(as.numeric(df$table31d_sumrow7), na.rm = TRUE)

```

\begin{table}[H]
\centering
\caption{عدد الشعب حسب الجنس والصف}
\resizebox{\textwidth}{!}{%
\begin{tabular}{@{}|c|ccc|ccc|ccccccccc|@{}}
\toprule
\multirow{3}{*}{\textbf{الصف}} & \multicolumn{3}{c|}{\textbf{\begin{tabular}[c]{@{}c@{}}عدد التلامذة التاركون حسب الصف\\ والجنس للعام الدراسي `r by`\end{tabular}}}            & \multicolumn{3}{c|}{\textbf{\begin{tabular}[c]{@{}c@{}}عدد التلامذة الناجحين للعام \\ الدراسي `r ay` حسب الصف والجنس\end{tabular}}}           & \multicolumn{9}{c|}{\textbf{\begin{tabular}[c]{@{}c@{}}عدد التلامذة الراسبين حسب اسباب الرسوب\\ والصف والجنس للعام الدراسي `r ay`\end{tabular}}}                                                                                                                                                                         \\ \cmidrule(l){2-16} 
                               & \multicolumn{1}{C{1.3cm}|}{\multirow{2}{*}{\textbf{بنين}}} & \multicolumn{1}{C{1.3cm}|}{\multirow{2}{*}{\textbf{بنات}}} & \multirow{2}{*}{\textbf{المجموع}} & \multicolumn{1}{C{1.3cm}|}{\multirow{2}{*}{\textbf{بنين}}} & \multicolumn{1}{C{1.3cm}|}{\multirow{2}{*}{\textbf{بنات}}} & \multirow{2}{*}{\textbf{المجموع}} & \multicolumn{2}{c|}{\textbf{الفشل في الامتحان}}                         & \multicolumn{2}{c|}{\textbf{تجاوز ايام الغياب}}                         & \multicolumn{2}{c|}{\textbf{أسباب أخرى}}                                & \multicolumn{3}{c|}{\textbf{المجموع}}                                                      \\ \cmidrule(l){8-16} 
                               & \multicolumn{1}{c|}{}                               & \multicolumn{1}{c|}{}                               &                                   & \multicolumn{1}{c|}{}                               & \multicolumn{1}{c|}{}                               &                                   & \multicolumn{1}{c|}{\textbf{بنون}} & \multicolumn{1}{c|}{\textbf{بنات}} & \multicolumn{1}{c|}{\textbf{بنون}} & \multicolumn{1}{c|}{\textbf{بنات}} & \multicolumn{1}{c|}{\textbf{بنون}} & \multicolumn{1}{c|}{\textbf{بنات}} & \multicolumn{1}{c|}{\textbf{بنون}} & \multicolumn{1}{c|}{\textbf{بنات}} & \textbf{المجموع} \\ \midrule
\textbf{الاول}                 & \multicolumn{1}{c|}{`r c11`}                        & \multicolumn{1}{c|}{`r c21`}                        & `r c31`                           & \multicolumn{1}{c|}{`r c41`}                        & \multicolumn{1}{c|}{`r c51`}                        & `r c61`                           & \multicolumn{1}{c|}{`r c71`}       & \multicolumn{1}{c|}{`r c81`}       & \multicolumn{1}{c|}{`r c91`}       & \multicolumn{1}{c|}{`r c101`}      & \multicolumn{1}{c|}{`r c111`}      & \multicolumn{1}{c|}{`r c121`}      & \multicolumn{1}{c|}{`r c131`}      & \multicolumn{1}{c|}{`r c141`}      & `r c151`         \\ \midrule
\textbf{الثاني}                & \multicolumn{1}{c|}{`r c12`}                        & \multicolumn{1}{c|}{`r c22`}                        & `r c32`                           & \multicolumn{1}{c|}{`r c42`}                        & \multicolumn{1}{c|}{`r c52`}                        & `r c62`                           & \multicolumn{1}{c|}{`r c72`}       & \multicolumn{1}{c|}{`r c82`}       & \multicolumn{1}{c|}{`r c92`}       & \multicolumn{1}{c|}{`r c102`}      & \multicolumn{1}{c|}{`r c112`}      & \multicolumn{1}{c|}{`r c122`}      & \multicolumn{1}{c|}{`r c132`}      & \multicolumn{1}{c|}{`r c142`}      & `r c152`         \\ \midrule
\textbf{الثالث}                & \multicolumn{1}{c|}{`r c13`}                        & \multicolumn{1}{c|}{`r c23`}                        & `r c33`                           & \multicolumn{1}{c|}{`r c43`}                        & \multicolumn{1}{c|}{`r c53`}                        & `r c63`                           & \multicolumn{1}{c|}{`r c73`}       & \multicolumn{1}{c|}{`r c83`}       & \multicolumn{1}{c|}{`r c93`}       & \multicolumn{1}{c|}{`r c103`}      & \multicolumn{1}{c|}{`r c113`}      & \multicolumn{1}{c|}{`r c123`}      & \multicolumn{1}{c|}{`r c133`}      & \multicolumn{1}{c|}{`r c143`}      & `r c153`         \\ \midrule
\textbf{الرابع}                & \multicolumn{1}{c|}{`r c14`}                        & \multicolumn{1}{c|}{`r c24`}                        & `r c34`                           & \multicolumn{1}{c|}{`r c44`}                        & \multicolumn{1}{c|}{`r c54`}                        & `r c64`                           & \multicolumn{1}{c|}{`r c74`}       & \multicolumn{1}{c|}{`r c84`}       & \multicolumn{1}{c|}{`r c94`}       & \multicolumn{1}{c|}{`r c104`}      & \multicolumn{1}{c|}{`r c114`}      & \multicolumn{1}{c|}{`r c124`}      & \multicolumn{1}{c|}{`r c134`}      & \multicolumn{1}{c|}{`r c144`}      & `r c154`         \\ \midrule
\textbf{الخامس}                & \multicolumn{1}{c|}{`r c15`}                        & \multicolumn{1}{c|}{`r c25`}                        & `r c35`                           & \multicolumn{1}{c|}{`r c45`}                        & \multicolumn{1}{c|}{`r c55`}                        & `r c65`                           & \multicolumn{1}{c|}{`r c75`}       & \multicolumn{1}{c|}{`r c85`}       & \multicolumn{1}{c|}{`r c95`}       & \multicolumn{1}{c|}{`r c105`}      & \multicolumn{1}{c|}{`r c115`}      & \multicolumn{1}{c|}{`r c125`}      & \multicolumn{1}{c|}{`r c135`}      & \multicolumn{1}{c|}{`r c145`}      & `r c155`         \\ \midrule
\textbf{السادس}                & \multicolumn{1}{c|}{`r c16`}                        & \multicolumn{1}{c|}{`r c26`}                        & `r c36`                           & \multicolumn{1}{c|}{`r c46`}                        & \multicolumn{1}{c|}{`r c56`}                        & `r c66`                           & \multicolumn{1}{c|}{`r c76`}       & \multicolumn{1}{c|}{`r c86`}       & \multicolumn{1}{c|}{`r c96`}       & \multicolumn{1}{c|}{`r c106`}      & \multicolumn{1}{c|}{`r c116`}      & \multicolumn{1}{c|}{`r c126`}      & \multicolumn{1}{c|}{`r c136`}      & \multicolumn{1}{c|}{`r c146`}      & `r c156`         \\ \midrule
\textbf{المجموع}               & \multicolumn{1}{c|}{`r c17`}                        & \multicolumn{1}{c|}{`r c27`}                        & `r c37`                           & \multicolumn{1}{c|}{`r c47`}                        & \multicolumn{1}{c|}{`r c57`}                        & `r c67`                           & \multicolumn{1}{c|}{`r c77`}       & \multicolumn{1}{c|}{`r c87`}       & \multicolumn{1}{c|}{`r c97`}       & \multicolumn{1}{c|}{`r c107`}      & \multicolumn{1}{c|}{`r c117`}      & \multicolumn{1}{c|}{`r c127`}      & \multicolumn{1}{c|}{`r c137`}      & \multicolumn{1}{c|}{`r c147`}      & `r c157`         \\ \bottomrule
\end{tabular}
}
\end{table}