
```{r table_v1_4, include=FALSE}

#class 1
c11 <- sum(df$form6_1a_2, na.rm = TRUE)
c12 <- sum(df$form6_1a_3, na.rm = TRUE)
c13 <- sum(df$form6_1a_4, na.rm = TRUE)

#class 2
c21 <- sum(df$form6_1a_6, na.rm = TRUE)
c22 <- sum(df$form6_1a_7, na.rm = TRUE)
c23 <- sum(df$form6_1a_8, na.rm = TRUE)

#class 3
c31 <- sum(df$form6_1a_10, na.rm = TRUE)
c32 <- sum(df$form6_1a_11, na.rm = TRUE)
c33 <- sum(df$form6_1a_12, na.rm = TRUE)

#class 4
c41 <- sum(df$form6_1a_14, na.rm = TRUE)
c42 <- sum(df$form6_1a_15, na.rm = TRUE)
c43 <- sum(df$form6_1a_16, na.rm = TRUE)

#class 5
c51 <- sum(df$form6_1a_18, na.rm = TRUE)
c52 <- sum(df$form6_1a_19, na.rm = TRUE)
c53 <- sum(df$form6_1a_20, na.rm = TRUE)
###################################################
#class 6
c61 <- sum(df$form6_10a1_2, na.rm = TRUE)
c62 <- sum(df$form6_10a2_2, na.rm = TRUE)
c63 <- sum(df$form6_10a3_2, na.rm = TRUE)

#class 7
c71 <- sum(df$form6_10a1_4, na.rm = TRUE)
c72 <- sum(df$form6_10a2_4, na.rm = TRUE)
c73 <- sum(df$form6_10a3_4, na.rm = TRUE)

#class 8
c81 <- sum(df$form6_10a1_6, na.rm = TRUE)
c82 <- sum(df$form6_10a2_6, na.rm = TRUE)
c83 <- sum(df$form6_10a3_6, na.rm = TRUE)

#class 9
c91 <- sum(df$form6_10a1_8, na.rm = TRUE)
c92 <- sum(df$form6_10a2_8, na.rm = TRUE)
c93 <- sum(df$form6_10a3_8, na.rm = TRUE)

#class 10
c101 <- sum(df$form6_10a1_10, na.rm = TRUE)
c102 <- sum(df$form6_10a2_10, na.rm = TRUE)
c103 <- sum(df$form6_10a3_10, na.rm = TRUE)

#class 11
c111 <- sum(df$form6_10a1_12, na.rm = TRUE)
c112 <- sum(df$form6_10a2_12, na.rm = TRUE)
c113 <- sum(df$form6_10a3_12, na.rm = TRUE)

#class 12
c121 <- sum(df$form6_10a1_14, na.rm = TRUE)
c122 <- sum(df$form6_10a2_14, na.rm = TRUE)
c123 <- sum(df$form6_10a3_14, na.rm = TRUE)

#class 13
c131 <- sum(df$form6_10a1_16, na.rm = TRUE)
c132 <- sum(df$form6_10a2_16, na.rm = TRUE)
c133 <- sum(df$form6_10a3_16, na.rm = TRUE)

#class 14
c141 <- sum(df$form6_10a1_18, na.rm = TRUE)
c142 <- sum(df$form6_10a2_18, na.rm = TRUE)
c143 <- sum(df$form6_10a3_18, na.rm = TRUE)

#class 15
c151 <- sum(df$form6_10a1_20, na.rm = TRUE)
c152 <- sum(df$form6_10a2_20, na.rm = TRUE)
c153 <- sum(df$form6_10a3_20, na.rm = TRUE)

#class 16
c161 <- sum(df$form6_10a1_22, na.rm = TRUE)
c162 <- sum(df$form6_10a2_22, na.rm = TRUE)
c163 <- sum(df$form6_10a3_22, na.rm = TRUE)

```



\begin{table}[H]
\centering
\caption{عدد الهيئات التعليمية حسب العنوان الوظيفي والشهادة}
\resizebox{\textwidth}{!}{%
\begin{tabular}{@{}|c|ccccc|cccccccccccl|@{}}
\toprule
\multirow{3}{*}{الجنس} & \multicolumn{5}{c|}{\multirow{2}{*}{الهيئة التعليمية حسب العنوان الوظيفي}}                                                          & \multicolumn{12}{c|}{الهيئة التعليمية حسب العنوان والشهادة}                                                                                                                                                                                                                                                                                                                                                                                                                                                                           \\ \cmidrule(l){7-18} 
                       & \multicolumn{5}{c|}{}                                                                                                               & \multicolumn{1}{c|}{\multirow{2}{*}{دورات تربوية}} & \multicolumn{1}{c|}{\multirow{2}{*}{دبلوم تعليمي}} & \multicolumn{1}{c|}{\multirow{2}{*}{دبلوم عام}} & \multicolumn{1}{c|}{\multirow{2}{*}{\begin{tabular}[c]{@{}c@{}}دبلوم فنون\\ جميلة\end{tabular}}} & \multicolumn{2}{c|}{جامعية}                                           & \multicolumn{3}{c|}{دراسات عليا}                                                                & \multicolumn{1}{c|}{\multirow{2}{*}{اخــرى}} & \multicolumn{2}{c|}{\multirow{2}{*}{المجموع}} \\ \cmidrule(lr){2-6} \cmidrule(lr){11-15}
                       & \multicolumn{1}{c|}{مدير}    & \multicolumn{1}{c|}{معاون}   & \multicolumn{1}{c|}{معلم}    & \multicolumn{1}{c|}{مرشد}    & المجموع & \multicolumn{1}{c|}{}                              & \multicolumn{1}{c|}{}                              & \multicolumn{1}{c|}{}                           & \multicolumn{1}{c|}{}                                                                            & \multicolumn{1}{c|}{تربوية تعليمية} & \multicolumn{1}{c|}{غير تربوية} & \multicolumn{1}{c|}{دبلوم عالي} & \multicolumn{1}{c|}{ماجستير}  & \multicolumn{1}{c|}{دكتوراه}  & \multicolumn{1}{c|}{}                        & \multicolumn{2}{c|}{}                         \\ \midrule
ذكــــــور             & \multicolumn{1}{c|}{`r c11`} & \multicolumn{1}{c|}{`r c21`} & \multicolumn{1}{c|}{`r c31`} & \multicolumn{1}{c|}{`r c41`} & `r c51` & \multicolumn{1}{c|}{`r c61`}                       & \multicolumn{1}{c|}{`r c71`}                       & \multicolumn{1}{c|}{`r c81`}                    & \multicolumn{1}{c|}{`r c91`}                                                                     & \multicolumn{1}{c|}{`r c101`}       & \multicolumn{1}{c|}{`r c111`}   & \multicolumn{1}{c|}{`r c121`}   & \multicolumn{1}{c|}{`r c131`} & \multicolumn{1}{c|}{`r c141`} & \multicolumn{1}{c|}{`r c151`}                & \multicolumn{2}{c|}{`r c161`}                 \\ \midrule
انــــــــاث           & \multicolumn{1}{c|}{`r c12`} & \multicolumn{1}{c|}{`r c22`} & \multicolumn{1}{c|}{`r c32`} & \multicolumn{1}{c|}{`r c42`} & `r c52` & \multicolumn{1}{c|}{`r c62`}                       & \multicolumn{1}{c|}{`r c72`}                       & \multicolumn{1}{c|}{`r c82`}                    & \multicolumn{1}{c|}{`r c92`}                                                                     & \multicolumn{1}{c|}{`r c102`}       & \multicolumn{1}{c|}{`r c112`}   & \multicolumn{1}{c|}{`r c122`}   & \multicolumn{1}{c|}{`r c132`} & \multicolumn{1}{c|}{`r c142`} & \multicolumn{1}{c|}{`r c152`}                & \multicolumn{2}{c|}{`r c162`}                 \\ \midrule
المجموع                & \multicolumn{1}{c|}{`r c13`} & \multicolumn{1}{c|}{`r c23`} & \multicolumn{1}{c|}{`r c33`} & \multicolumn{1}{c|}{`r c43`} & `r c53` & \multicolumn{1}{c|}{`r c63`}                       & \multicolumn{1}{c|}{`r c73`}                       & \multicolumn{1}{c|}{`r c83`}                    & \multicolumn{1}{c|}{`r c93`}                                                                     & \multicolumn{1}{c|}{`r c103`}       & \multicolumn{1}{c|}{`r c113`}   & \multicolumn{1}{c|}{`r c123`}   & \multicolumn{1}{c|}{`r c133`} & \multicolumn{1}{c|}{`r c143`} & \multicolumn{1}{c|}{`r c153`}                & \multicolumn{2}{c|}{`r c163`}                 \\ \bottomrule
\end{tabular}
}
\end{table}