```{r table_v1_1, include=FALSE}

c11 <- nrow(df[which(df$q6 == "1" &df$q20 == "1"),])
c12 <- nrow(df[which(df$q6 == "2" &df$q20 == "1"),])
c13 <- c11 + c12

c21 <- nrow(df[which(df$q6 == "1" &df$q20 == "2"),])
c22 <- nrow(df[which(df$q6 == "2" &df$q20 == "2"),])
c23 <- c21 + c22

c31 <- nrow(df[which(df$q6 == "1" &df$q20 == "3"),])
c32 <- nrow(df[which(df$q6 == "2" &df$q20 == "3"),])
c33 <- c31 + c32 

c41 <- c11 + c21 + c31
c42 <- c12 + c22 + c32
c43 <- c41 + c42 

c51 <- sum(df$table25a_32[df$q6 == "1"], na.rm = TRUE)
c52 <- sum(df$table25a_32[df$q6 == "2"], na.rm = TRUE)
c53 <- c51 + c52

c61 <- sum(df$table25a_33[df$q6 == "1"], na.rm = TRUE)
c62 <- sum(df$table25a_33[df$q6 == "2"], na.rm = TRUE)
c63 <- c61 + c62

c71 <- c51 + c61
c72 <- c52 + c62
c73 <- c71 + c72

c81 <- sum(df$table26a_32[df$q6 == "1"], na.rm = TRUE) + 
       sum(df$table26b_27[df$q6 == "1"], na.rm = TRUE) +
       sum(df$table26c_27[df$q6 == "1"], na.rm = TRUE) + 
       sum(df$table26d_27[df$q6 == "1"], na.rm = TRUE) + 
       sum(df$table26e_27[df$q6 == "1"], na.rm = TRUE) + 
       sum(df$table26f_27[df$q6 == "1"], na.rm = TRUE)

c82 <- sum(df$table26a_32[df$q6 == "2"], na.rm = TRUE) + 
       sum(df$table26b_27[df$q6 == "2"], na.rm = TRUE) +
       sum(df$table26c_27[df$q6 == "2"], na.rm = TRUE) + 
       sum(df$table26d_27[df$q6 == "2"], na.rm = TRUE) + 
       sum(df$table26e_27[df$q6 == "2"], na.rm = TRUE) + 
       sum(df$table26f_27[df$q6 == "2"], na.rm = TRUE)

c83 <- c81 + c82

c91 <- sum(df$table26a_33[df$q6 == "1"], na.rm = TRUE) + 
       sum(df$table26b_28[df$q6 == "1"], na.rm = TRUE) +
       sum(df$table26c_28[df$q6 == "1"], na.rm = TRUE) + 
       sum(df$table26d_28[df$q6 == "1"], na.rm = TRUE) + 
       sum(df$table26e_28[df$q6 == "1"], na.rm = TRUE) + 
       sum(df$table26f_28[df$q6 == "1"], na.rm = TRUE)

c92 <- sum(df$table26a_33[df$q6 == "2"], na.rm = TRUE) +
       sum(df$table26b_28[df$q6 == "2"], na.rm = TRUE) +
       sum(df$table26c_28[df$q6 == "2"], na.rm = TRUE) + 
       sum(df$table26d_28[df$q6 == "2"], na.rm = TRUE) + 
       sum(df$table26e_28[df$q6 == "2"], na.rm = TRUE) + 
       sum(df$table26f_28[df$q6 == "2"], na.rm = TRUE)

c93 <- c91 + c92
######################################################
c101 <- c81 + c91

c102 <- c82 + c92

c103 <- c101 + c102
######################################################
c111 <- sum(df$form6_1a_18[df$q6 == "1"], na.rm = TRUE)

c112 <- sum(df$form6_1a_18[df$q6 == "2"], na.rm = TRUE)

c113 <- c111 + c112
######################################################
c121 <- sum(df$form6_1a_19[df$q6 == "1"], na.rm = TRUE)

c122 <- sum(df$form6_1a_19[df$q6 == "2"], na.rm = TRUE)

c123 <- c121 + c122
######################################################
c131 <- c111 + c121

c132 <- c112 + c122

c133 <- c131 + c132
######################################################
c141 <- nrow(df[df$q6 == "1" &df$q22 == "1",])

c142 <- nrow(df[df$q6 == "2" &df$q22 == "1",])

c143 <- c141 + c142
#####################################################
c151 <- nrow(df[df$q6 == "1" &df$q22 == "2",])

c152 <- nrow(df[df$q6 == "2" &df$q22 == "2",])

c153 <- c151 + c152
#####################################################
c161 <- nrow(df[df$q6 == "1" &df$q21 == "1",])

c162 <- nrow(df[df$q6 == "2" &df$q22 == "1",])

c163 <- c161 + c162
####################################################
c171 <- nrow(df[df$q6 == "1" &df$q21 == "2",])

c172 <- nrow(df[df$q6 == "2" &df$q22 == "2",])

c173 <- c171 + c172
###################################################
c181 <- nrow(df[df$q6 == "1" &df$q21 == "3",])

c182 <- nrow(df[df$q6 == "2" &df$q22 == "3",])

c183 <- c181 + c182
##################################################
c191 <- nrow(df[df$q6 == "1" &df$q21 == "4",])

c192 <- nrow(df[df$q6 == "2" &df$q22 == "4",])

c193 <- c191 + c192
#################################################
c201 <- c161 +c171 + c181 + c191
c202 <- c162 +c172 + c182 + c192
c203 <- c201 + c202
################################################
c211 <- nrow(df[df$q6 == "1" &df$q15 == "1",])

c212 <- nrow(df[df$q6 == "2" &df$q15 == "1",])

c213 <- c211 + c212

```

\begin{table}[H]
\centering
\caption{عدد المدارس والتلامذة الموجودين والمقبولين الجدد وعدد اعضاء الهيئة التعليمية واستقلالية المدرسة ( الصباحي والمسائي )}
\resizebox{\textwidth}{!}{%
\begin{tabular}{@{}|c|cccc|ccc|ccc|ccc|cc|ccccc|c|@{}}
\toprule
\multirow{2}{*}{الجنس} & \multicolumn{4}{c|}{عدد المدارس}                                                                     & \multicolumn{3}{c|}{\begin{tabular}[c]{@{}c@{}}عدد التلامذة المقبولين ( الجدد )\\ في الصف الاول الابتدائي\end{tabular}} & \multicolumn{3}{c|}{عدد التلامذة الموجودين}                            & \multicolumn{3}{c|}{عدد اعضاء الهيئة التعليمية}                          & \multicolumn{2}{c|}{\begin{tabular}[c]{@{}c@{}}عدد المدارس\\ حسب الاستقلالية\end{tabular}} & \multicolumn{5}{c|}{عدد المدارس حسب الدوام}                                                                                                                                           & \multirow{2}{*}{\begin{tabular}[c]{@{}c@{}}مدارس\\ الفتح\\ الجديد\end{tabular}} \\ \cmidrule(lr){2-21}
                       & \multicolumn{1}{c|}{بنون}    & \multicolumn{1}{c|}{بنات}    & \multicolumn{1}{c|}{مختلطة}  & المجموع & \multicolumn{1}{c|}{بنون}                     & \multicolumn{1}{c|}{بنات}                     & المجموع                 & \multicolumn{1}{c|}{بنون}    & \multicolumn{1}{c|}{بنات}    & المجموع  & \multicolumn{1}{c|}{ذكور}     & \multicolumn{1}{c|}{اناث}     & المجموع  & \multicolumn{1}{c|}{اصلية}                             & ضيف                               & \multicolumn{1}{c|}{صباحاً}   & \multicolumn{1}{c|}{ظهرا}     & \multicolumn{1}{c|}{\begin{tabular}[c]{@{}c@{}}صباحا\\ وظهرا\end{tabular}} & \multicolumn{1}{c|}{مساءاً}   & المجموع  &                                                                                 \\ \midrule
حضـــر                 & \multicolumn{1}{c|}{`r c11`} & \multicolumn{1}{c|}{`r c21`} & \multicolumn{1}{c|}{`r c31`} & `r c41` & \multicolumn{1}{c|}{`r c51`}                  & \multicolumn{1}{c|}{`r c61`}                  & `r c71`                 & \multicolumn{1}{c|}{`r c81`} & \multicolumn{1}{c|}{`r c91`} & `r c101` & \multicolumn{1}{c|}{`r c111`} & \multicolumn{1}{c|}{`r c121`} & `r c131` & \multicolumn{1}{c|}{`r c141`}                          & `r c151`                          & \multicolumn{1}{c|}{`r c161`} & \multicolumn{1}{c|}{`r c171`} & \multicolumn{1}{c|}{`r c181`}                                              & \multicolumn{1}{c|}{`r c191`} & `r c201` & `r c211`                                                                        \\ \midrule
ريـــــف               & \multicolumn{1}{c|}{`r c12`} & \multicolumn{1}{c|}{`r c22`} & \multicolumn{1}{c|}{`r c32`} & `r c42` & \multicolumn{1}{c|}{`r c52`}                  & \multicolumn{1}{c|}{`r c62`}                  & `r c72`                 & \multicolumn{1}{c|}{`r c82`} & \multicolumn{1}{c|}{`r c92`} & `r c102` & \multicolumn{1}{c|}{`r c112`} & \multicolumn{1}{c|}{`r c122`} & `r c132` & \multicolumn{1}{c|}{`r c142`}                          & `r c152`                          & \multicolumn{1}{c|}{`r c162`} & \multicolumn{1}{c|}{`r c172`} & \multicolumn{1}{c|}{`r c182`}                                              & \multicolumn{1}{c|}{`r c192`} & `r c202` & `r c212`                                                                        \\ \midrule
المجموع                & \multicolumn{1}{c|}{`r c13`} & \multicolumn{1}{c|}{`r c23`} & \multicolumn{1}{c|}{`r c33`} & `r c43` & \multicolumn{1}{c|}{`r c53`}                  & \multicolumn{1}{c|}{`r c63`}                  & `r c73`                 & \multicolumn{1}{c|}{`r c83`} & \multicolumn{1}{c|}{`r c93`} & `r c103` & \multicolumn{1}{c|}{`r c113`} & \multicolumn{1}{c|}{`r c123`} & `r c133` & \multicolumn{1}{c|}{`r c143`}                          & `r c153`                          & \multicolumn{1}{c|}{`r c163`} & \multicolumn{1}{c|}{`r c173`} & \multicolumn{1}{c|}{`r c183`}                                              & \multicolumn{1}{c|}{`r c193`} & `r c203` & `r c213`                                                                        \\ \bottomrule
\end{tabular}
}
\end{table}