```{r table_v1a_3, include=FALSE}

#class1
c11 <- sum(as.numeric(df$app21_12a1_22[df$app21_7_2 == "1"]), na.rm = TRUE)
c12 <- sum(as.numeric(df$app21_12a1_22[df$app21_7_3 == "1"]), na.rm = TRUE)
c13 <- sum(as.numeric(df$app21_12a1_22[df$app21_7_4 == "1"]), na.rm = TRUE)
c14 <- sum(as.numeric(df$app21_12a1_22[df$app21_7_sumrow1 == "1"]), na.rm = TRUE)

#class2
c21 <- sum(as.numeric(df$app21_12a1_22[df$app21_7_7 == "1"]), na.rm = TRUE)
c22 <- sum(as.numeric(df$app21_12a1_22[df$app21_7_8 == "1"]), na.rm = TRUE)
c23 <- sum(as.numeric(df$app21_12a1_22[df$app21_7_9 == "1"]), na.rm = TRUE)
c24 <- sum(as.numeric(df$app21_12a1_22[df$app21_7_sumrow2 == "1"]), na.rm = TRUE)

#class3
c31 <- sum(as.numeric(df$app21_12a1_22[df$app21_7_12 == "1"]), na.rm = TRUE)
c32 <- sum(as.numeric(df$app21_12a1_22[df$app21_7_13 == "1"]), na.rm = TRUE)
c33 <- sum(as.numeric(df$app21_12a1_22[df$app21_7_14 == "1"]), na.rm = TRUE)
c34 <- sum(as.numeric(df$app21_12a1_22[df$app21_7_sumrow3 == "1"]), na.rm = TRUE)

#class4
c41 <- sum(as.numeric(df$app21_12a1_22[df$app21_7_17 == "1"]), na.rm = TRUE)
c42 <- sum(as.numeric(df$app21_12a1_22[df$app21_7_18 == "1"]), na.rm = TRUE)
c43 <- sum(as.numeric(df$app21_12a1_22[df$app21_7_19 == "1"]), na.rm = TRUE)
c44 <- sum(as.numeric(df$app21_12a1_22[df$app21_7_sumrow4 == "1"]), na.rm = TRUE)

#class5
c51 <- sum(as.numeric(df$app21_12a1_22[df$app21_7_22 == "1"]), na.rm = TRUE)
c52 <- sum(as.numeric(df$app21_12a1_22[df$app21_7_23 == "1"]), na.rm = TRUE)
c53 <- sum(as.numeric(df$app21_12a1_22[df$app21_7_24 == "1"]), na.rm = TRUE)
c54 <- sum(as.numeric(df$app21_12a1_22[df$app21_7_sumrow5 == "1"]), na.rm = TRUE)

#class6
c61 <- sum(as.numeric(df$app21_12a1_22[df$app21_7_27 == "1"]), na.rm = TRUE)
c62 <- sum(as.numeric(df$app21_12a1_22[df$app21_7_28 == "1"]), na.rm = TRUE)
c63 <- sum(as.numeric(df$app21_12a1_22[df$app21_7_29 == "1"]), na.rm = TRUE)
c64 <- sum(as.numeric(df$app21_12a1_22[df$app21_7_sumrow6 == "1"]), na.rm = TRUE)

#total
c71 <- sum(as.numeric(df$app21_12a1_22[df$app21_7_32 == "1"]), na.rm = TRUE)
c72 <- sum(as.numeric(df$app21_12a1_22[df$app21_7_33 == "1"]), na.rm = TRUE)
c73 <- sum(as.numeric(df$app21_12a1_22[df$app21_7_34 == "1"]), na.rm = TRUE)
c74 <- sum(as.numeric(df$app21_12a1_22[df$app21_7_sumrow7 == "1"]), na.rm = TRUE)





```

\begin{table}[H]
\centering
\caption{عدد الشعب لصفوف التربية الخاصة}
\begin{tabular}{@{}|c|cl|cl|cl|cl|cl|cl|cl|@{}}
\toprule
\textbf{الجنس}   & \multicolumn{2}{c|}{\textbf{الصف الاول}} & \multicolumn{2}{c|}{\textbf{الصف الثاني}} & \multicolumn{2}{c|}{\textbf{الصف الثالث}} & \multicolumn{2}{c|}{\textbf{الصف الرابع}} & \multicolumn{2}{c|}{\textbf{الصف الخامس}} & \multicolumn{2}{c|}{\textbf{الصف السادس}} & \multicolumn{2}{C{3cm}|}{\textbf{المجموع}} \\ \midrule
\textbf{بنون}    & \multicolumn{2}{c|}{`r c11`}             & \multicolumn{2}{c|}{`r c21`}              & \multicolumn{2}{c|}{`r c31`}              & \multicolumn{2}{c|}{`r c41`}              & \multicolumn{2}{c|}{`r c51`}              & \multicolumn{2}{c|}{`r c51`}              & \multicolumn{2}{c|}{`r c61`}          \\ \midrule
\textbf{بنات}    & \multicolumn{2}{c|}{`r c12`}             & \multicolumn{2}{c|}{`r c22`}              & \multicolumn{2}{c|}{`r c32`}              & \multicolumn{2}{c|}{`r c42`}              & \multicolumn{2}{c|}{`r c52`}              & \multicolumn{2}{c|}{`r c52`}              & \multicolumn{2}{c|}{`r c62`}          \\ \midrule
\textbf{مختلط}   & \multicolumn{2}{c|}{`r c13`}             & \multicolumn{2}{c|}{`r c23`}              & \multicolumn{2}{c|}{`r c33`}              & \multicolumn{2}{c|}{`r c43`}              & \multicolumn{2}{c|}{`r c53`}              & \multicolumn{2}{c|}{`r c53`}              & \multicolumn{2}{c|}{`r c63`}          \\ \midrule
\textbf{المجموع} & \multicolumn{2}{c|}{`r c14`}             & \multicolumn{2}{c|}{`r c24`}              & \multicolumn{2}{c|}{`r c34`}              & \multicolumn{2}{c|}{`r c44`}              & \multicolumn{2}{c|}{`r c54`}              & \multicolumn{2}{c|}{`r c54`}              & \multicolumn{2}{c|}{`r c64`}          \\ \bottomrule
\end{tabular}
\end{table}